<?php
require($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = "Typ";
$strModified = "Ver&auml;ndert";
$strSize = "Gr&ouml;sse";
$fbRefresh = "Aktualisieren";
$fbProperties = "Eigenschaften";
$fbNewFolder = "Neuer Ordner";
$fbDelete = "L&ouml;schen";
$fbCut = "Ausschneiden";
$fbPaste = "Einf&uuml;gen";
$fbCopy = "Kopieren";
$fbFiletypes = "Dateitypen";
$fbPath = "Pfad";
$fbFolders = "Ordner";
$fbNoSelect = "Sie haben kein Element ausgewählt. Zum Auswählen auf das Symbol neben dem Namen klicken.";
$fbConfirmDelete = "Bestätigung zum Löschen";
$fbGeneral = "Allgemein";
$fbConfirmOverwrite = "Bestätigung zum überschreiben";
$strOverwritePrefix = "Sind Sie sicher, dass Sie ";
$strOverwriteSuffix = " überschreiben möchten?";
$fbDescription = "Beschreibung";
$fbLocation = "Standort";
$fbUpload = "Hochladen";
$fbUpload_text = "Datei f&uuml;r den Upload ausw&auml;hlen";
$fbUpload_nofile = "Keine Datei empfangen.";
$fbFolderExists = "Der Ordner ist bereits vorhanden.";
$fbEmailFile = "Email-Datei";
$fbFolder = "Ordner";
$fbSelect = "Datei w&auml;hlen...";
$fbNoFile = "Die hochzuladende Datei ist zu gross.<br /> Die maximale Grösse ist: ";
$fbPleaseWait = "Bitte warten. Daten&uuml;bertragung...";
$fbFilename = "Dateiname";
$fbUpLevel = "Ebene h&ouml;her";
$fbItems = "Element(e)";
$fbFolderSize = "Gr&ouml;sse des Ordners";
$fbMaxUploadSize = "Maximale Gr&ouml;sse";
$ml_file_too_big = "Der Dateianhang ist zu gross, die maximale Gr&ouml;sse ist: ";
$cmdSearch = "Suchen";
$fbNameExists = "Der Name ist bereits vorhanden.";
$fbThis = 'Dies';
$fbFiles = 'Dateien';
$fs_no_multi_select = 'Mit dieser Option ist nur ein Element selektierbar';
$cms_untitled = 'Unbenannt';
$cms_insert_file = 'Datei einf&uuml;gen';
$cms_preview = 'Voransicht';
$cms_keywords = 'Schl&uuml;sselw&ouml;rter';
$cms_priority = 'Prioritaet';
$cms_hide_folder = 'Diesen Ordner auf der Seite verbergen';
$cms_theme = 'Thema';
$cms_use_go_auth = 'Wende die Authentifizierung von Group-Office auf dieser Seite an';
$cms_search_files_prefix = 'HTML Dateien, die das Wort';
$cms_search_files_suffix = 'enthalten, werden automatisch selektiert. Bitte auf \'Ok\' klicken, um die Selektion zu speichern.';
$cms_new_site = 'Neue Seite';
$cms_search_files = 'Dateien suchen';
$cms_subscribe = 'Abonnieren';
$cms_sites = 'Seite(n)';
$cms_style = 'Stil';
$cms_insert_file_url = 'URL einf&uuml;gen';
$cms_templates = 'Vorlage';
$cms_files = 'Dateien';
$cms_items = 'Element(e)';
$cms_header = 'Kopfteil';
$cms_footer = 'Fussteil';
$cms_new_theme = 'Neues Thema';
$cms_themes = 'Themen';
$cms_themes_menu = 'Themen';
$cms_all_sites = 'Alle Seiten';
$cms_your_sites = 'Meine Seiten';
$cms_cmd_new_site = 'Neue Seite';
$cms_template_items = 'Vorlagen(n)';
$cms_new_template_item = 'Neue Vorlage';
$cms_found_one = '1 Datei gefunden';
$cms_found = 'Dateien gefunden';
$cms_empty = 'Dieser Abschnitt ist leer und m&ouml;glicherweise in Wartung.';
$cms_new_page = 'Neue Seite';
$cms_search_words = 'Suchbegriff';
$cms_no_themes = 'Ihnen stehen noch keine Themen zur Verf&uuml;gung. Legen Sie bitte mindestens ein Thema an.';
$cms_edit_search_words = 'Suchbegriffe bearbeiten';
$cms_id = 'Seiten-ID';

$cms_cleanup = 'Aufr&auml;umen';
$cms_settings = 'Einstellungen';
$cms_site_exists = 'Es existiert bereits eine Seite mit diesem Namen.';
$cms_main_template = 'Hauptvorlage';
$cms_confirm_close = 'Alle &Auml;nderungen werden verloren gehen. Sind Sie sicher?';
$cms_additional_style = 'Vor dem Editor verborgener Stil';
$cms_restrict_editor = 'Den Editor auf vordefinierte Stile einschr&auml;nken';
$cms_enable_publish = 'Aktiviere die Ver&ouml;ffentlichung lokaler Webseiten';

$cms_path_not_writable = 'Der angegebene Pfad ist entweder ung&uuml;ltig oder fuer Group-Office nicht beschreibbar.';
$cms_publish = 'Ver&ouml;ffentlichung';
$cms_path_already_used = 'Der angegebene Pfad wird bereits von einer anderen Webseite verwendet.';
$cms_site_offline = 'Diese Seite ist zur Zeit inaktiv';

$cms_disable_publish = 'Seite deaktivieren';
$cms_publish_dynamic = 'Dynamisch ver&ouml;ffentlichen';
$cms_publish_static = 'Statisch ver&ouml;ffentlichen';

//2.05
$cms_sendmail_error = 'Ihre Nachricht konnte nicht versendet werden. Bitte erneut versuchen.';
$cms_sendmail_success = 'Vielen Dank. Ihre Nachricht wurde versandt.';
$cms_message = 'Nachricht';
$cms_subject = 'Betreff';
$cms_domain = 'Dom&auml;ne';
$cms_replace_filenames = 'Dateien umbenennen';

//2.06
$cms_multipage_display = 'Fasse alle Seiten der Ordner und die Startseiten der Unterordner zusammen';
$cms_hot_item = 'F&uuml;ge diese Seite den Favoriten hinzu';
$cms_normal_display = 'Zeige die Startseite dieses Ordners';

$cms_display_type = 'Wenn ein Besucher einen Ordner dieser Webseite &ouml;ffnet:';
$cms_read_more = 'Zeige mehr';
$cms_additional_style = 'Ein im Editor verwendeter Stil';
?>
