<?php
//Uncomment this line in new translations!
//require($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = "Type";
$strModified = "Modified";
$strSize = "Size";
$fbRefresh = "Refresh";
$fbProperties = "Properties";
$fbNewFolder = "New folder";
$fbDelete = "Delete";
$fbCut = "Cut";
$fbPaste = "Paste";
$fbCopy = "Copy";
$fbFiletypes = "Filetypes";
$fbPath = "Path";
$fbFolders = "Folders";
$fbNoSelect = "You didn't select an item. Click on an icon next to the name to select an item.";
$fbConfirmDelete = "Confirm delete";
$fbGeneral = "General";
$fbConfirmOverwrite = "Confirm overwrite";
$strOverwritePrefix = "Are you sure you want to overwrite ";
$strOverwriteSuffix = "?";
$fbDescription = "Description";
$fbLocation = "Location";
$fbUpload = "Upload";
$fbUpload_text = "Select file to upload";
$fbUpload_nofile = "No file was not recieved.";
$fbFolderExists = "The folder already exists.";
$fbFolder = "Folder";
$fbSelect = "Select file...";
$fbNoFile = "The file you tried to upload is too big.<br /> The maximum transferable filesize is set to: ";
$fbPleaseWait = "Please wait. Sending data...";
$fbFilename = "Filename";
$fbUpLevel = "Level up";
$fbItems = "item(s)";
$fbFolderSize = "Size of folder";
$fbMaxUploadSize = "Maximum size";
$ml_file_too_big = "The file you tried to attach is too big, the maximum filesize for attachments is set to: ";
$cmdSearch = "Search";
$fbNameExists = "The name already exists.";
$fbThis = 'this';
$fbFiles = 'Files';
$fs_no_multi_select = 'U can\'t select more then one item with this option';
$cms_untitled = 'Untitled';
$cms_insert_file = 'Insert file';
$cms_preview = 'Preview';
$cms_keywords = 'Keywords';
$cms_priority = 'Priority';
$cms_hide_folder = 'Hide this folder on the site';
$cms_theme = 'Theme';
$cms_use_go_auth = 'Use Group-Office authentication on this site';
$cms_search_files_prefix = 'The HTML files that contain the word';
$cms_search_files_suffix = 'are automatically selected. Click on \'Ok\' to save this selection.';
$cms_new_site = 'New site';
$cms_search_files = 'Search files';
$cms_subscribe = 'Subscribe';
$cms_sites = 'site(s)';
$cms_style = 'Style';
$cms_insert_file_url = 'Insert URL';
$cms_templates = 'Templates';
$cms_files = 'Files';
$cms_items = 'item(s)';
$cms_header = 'Header';
$cms_footer = 'Footer';
$cms_new_theme = 'New theme';
$cms_themes = 'theme(s)';
$cms_themes_menu = 'Themes';
$cms_all_sites = 'All sites';
$cms_your_sites = 'Your sites';
$cms_cmd_new_site = 'New site';
$cms_template_items = 'template(s)';
$cms_new_template_item = 'New template';
$cms_found_one = '1 file found';
$cms_found = 'files found';
$cms_empty = 'This section is empty and probably under maintanance.';
$cms_new_page = 'New page';
$cms_search_words = 'Search words';
$cms_no_themes = 'You don\'t have any themes yet. Create a theme first.';
$cms_edit_search_words = 'edit search words';
$cms_id = 'Site ID';

$cms_cleanup = 'Cleanup';
$cms_settings = 'Settings';
$cms_site_exists = 'A site with that name already exists';
$cms_main_template = 'Main';
$cms_confirm_close = 'Changes will be lost are you sure?';
$cms_additional_style = 'Style that is hidden from the editor';
$cms_restrict_editor = 'Restrict editor to predefined styles';
$cms_enable_publish = 'Enable local website publishing';

$cms_path_not_writable = 'The path you entered is invalid or not writable for Group-Office.';
$cms_publish = 'Publishing';
$cms_path_already_used = 'The path you entered is already in use by another website.';
$cms_site_offline = 'This site is currently taken offline';

$cms_disable_publish = 'Take site offline';
$cms_publish_dynamic = 'Publish dynamic';
$cms_publish_static = 'Publish static';

//2.05
$cms_sendmail_error = 'Your message could not be sent. Please try again.';
$cms_sendmail_success = 'Thank you. Your message has been sent.';
$cms_message = 'Message';
$cms_subject = 'Subject';
$cms_domain = 'Domain';
$cms_replace_filenames = 'Replace filenames';

//2.06
$cms_multipage_display = 'Display this folder in the multi page view';
$cms_hot_items = 'Display this folder in the hot items';
$cms_normal_display = 'Only display when accessed directly';

$cms_display_type = 'When a viewer opens a folder on the web page:';
$cms_site_normal_display = 'Display the first file of a folder';
$cms_site_multipage_display = 'Display a multipage view';
$cms_read_more = 'Read more';
?>
