<?php
require($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = "Tipo";
$strModified = "Modificato";
$strSize = "Dimensione";
$fbRefresh = "Aggiorna";
$fbProperties = "Proprietà";
$fbNewFolder = "Nuova cartella";
$fbDelete = "Elimina";
$fbCut = "Taglia";
$fbPaste = "Incolla";
$fbCopy = "Copia";
$fbFiletypes = "Tipi di file";
$fbPath = "Percorso";
$fbFolders = "Cartelle";
$fbNoSelect = "Non hai selezionato un elemento. Click su un'icona vicino al nome dell'elemento da selezionare.";
$fbConfirmDelete = "Confermi eliminazione";
$fbGeneral = "Generale";
$fbConfirmOverwrite = "Confirmi sovrascrittura";
$strOverwritePrefix = "Sei sicuro di sovrascrivere ";
$strOverwriteSuffix = "?";
$fbDescription = "Descrizione";
$fbLocation = "Posizione";
$fbUpload = "importazione";
$fbUpload_text = "Seleziona il file da importare";
$fbUpload_nofile = "Nessun file è stato ricevuto.";
$fbFolderExists = "La cartella esiste già.";
$fbEmailFile = "e-mail file";
$fbFolder = "Cartella";
$fbSelect = "Seleziona file...";
$fbNoFile = "Il file che hai importato è troppo grande.<br /> La dimensione massima per il trasferimento di un file è: ";
$fbPleaseWait = "Attendere prego. Invio dati in corso...";
$fbFilename = "Nome file";
$fbUpLevel = "livello superiore";
$fbItems = "elemento/i";
$fbFolderSize = "Dimensione della cartella";
$fbMaxUploadSize = "Dimensione massima";
$ml_file_too_big = "Il file che hai allegato è troppo grande, la dimensione massima è impostata a: ";
$cmdSearch = "Cerca";
$fbNameExists = "Il nome esiste già in questa cartella.";
$fbThis = 'questo';
$fbFiles = 'Documenti';
$fs_no_multi_select = 'Non puoi selezionare più di un elemento con questa opzione';

$cms_untitled = 'Senza titolo';
$cms_insert_file = 'Inserisci file';
$cms_preview = 'Anteprima';
$cms_keywords = 'Parole chiave';
$cms_priority = 'Priorità';
$cms_hide_folder = 'Nascondi questa cartella nel sito';
$cms_theme = 'Tema';
$cms_use_go_auth = 'Usa l\'autenticazione di Group-Office in questo sito';
$cms_search_files_prefix = 'I file HTML che contengono la parola';
$cms_search_files_suffix = 'sono selezionati automaticamente. Premi \''.$cmdOk.'\' per salvare questa selezione.';
$cms_new_site = 'Nuovo sito';
$cms_search_files = 'cerca file';
$cms_subscribe = 'sottoscrivi';
$cms_sites = 'sito/i';
$cms_style = 'Stile';
$cms_insert_file_url = 'Inserisci URL';
$cms_templates = 'templates';
$cms_files = 'file';
$cms_items = 'elemento/i';
$cms_header = 'Intestazione';
$cms_footer = 'Piede';
$cms_new_theme = 'nuovo tema';
$cms_themes = 'tema/i';
$cms_themes_menu = 'temi';
$cms_all_sites = 'tutti i siti';
$cms_your_sites = 'siti personali';
$cms_cmd_new_site = 'nuovo sito';
$cms_template_items = 'template';
$cms_new_template_item = 'nuovo template';

$cms_found_one = '1 file trovato';
$cms_found = 'file trovati';
$cms_empty = 'Questa pagina è vuota e probabilmente in manutenzione.';
$cms_new_page = 'nuova pagina';

$cms_search_words = 'Ricerca parole';
$cms_no_themes = 'Non hai nessun tema. Devi prima crearne uno.';
$cms_edit_search_words = 'modifica parole di ricerca';
$cms_id = 'Identificatore sito';


$cms_cleanup = 'Pulisci';
$cms_settings = 'Impostazioni';
$cms_site_exists = 'Un sito con questo nome esiste già';
$cms_main_template = 'Principale';
$cms_confirm_close = 'Le modifiche verranno perse, sei sicuro?';
$cms_additional_style = "Stile nascosto dall'editor";
$cms_restrict_editor = 'Consenti solo gli stili predefiniti';

// 1.93
$cms_enable_publish = 'Abilita pubblicazione del sito web locale';

$cms_path_not_writable = 'Il percorso inverito non è valido oppure non vi è permessa la scrittura per Group-Office.';
$cms_publish = 'Puubblica';
$cms_path_already_used = 'Il percorso inserito è già utilizzato da un altro sito web.';
$cms_site_offline = 'Questo sito è impostato off-line';

$cms_disable_publish = 'Imposta sito off-line';
$cms_publish_dynamic = 'Pubblicazione dinamica';
$cms_publish_static = 'Pubblicazione statica';

//2.05
$cms_sendmail_error = 'Il tuo messaggio non può essere spedito. Riprovate ancora.';
$cms_sendmail_success = 'Grazie. Il tuo messaggio è stato spedito.';
$cms_message = 'Messaggio';
$cms_subject = 'Oggetto';
$cms_domain = 'Dominio';
$cms_replace_filenames = 'Sostituisci i nomi dei file';

//2.06
$cms_multipage_display = 'Mostra questa cartella in una vista a più pagine';
$cms_hot_items = 'Display this folder in the hot items';
$cms_normal_display = 'Only display when accessed directly';

$cms_display_type = 'When a viewer opens a folder on the web page:';
$cms_site_normal_display = 'Display the first file of a folder';
$cms_site_multipage_display = 'Display a multipage view';

?>
