<?php
require($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = "Addressebog";
$contacts_no_contacts = "Der er ingen kontaktpersoner.";
$contacts_members = "Medlemmer";
$contacts_contacts = "Kontaktpersoner";
$contacts_add = "Ny kontaktperson";
$contacts_groups = "Grupper";
$contacts_other = "Andre kontaktpersoner";
$contacts_move_to_group = "Flyt valgte kontaktpersoner til gruppen...";
$groups_no_groups = "Der er ingen grupper";
$contacts_group = "Gruppe";
$contacts_empty_group = "Brug listen til at flytte kontaktpersoner til denne gruppe.";
$contacts_this_group = 'Denne gruppe';

$add_contacts_text = "Indtast medlemmets mailadresse og autorisationskode og klik på 'OK'";
$add_contacts_success = "Bruger tilføjet";
$add_contacts_wrong = "Forkert mailadresse eller autorisationskode.";
$add_personal_text = "Klik på 'OK' for at tilføje en kontakt. Felterne markeret med * skal udfyldes.";
$contacts_select = "Vælg de kontaktpersoner der skal tilføjes og klik på 'OK'.";
$contacts_select_title = "Kontaktpersoner";
$contact_profile = "Kontaktperson profil";
$user_profile = "Bruger profil";
$contacts_authorise = "Authorisation";
$contacts_add_member = "Tilføj medlem til dine kontakter";
$strConfirmSynchronise = "Dette vil opdate kontaktpersonen med data brugeren selv har indtastet. Ændringer du selv har lavet vil gå tabt. Er du sikker på du vil fortsætte?";
$contacts_import = "Importer";
$contacts_export = "Eksporter";
$contacts_export_text = "Vælg den type fil du vil oprette.";
$contacts_delete = "Slet";

$contacts_import_text = "Vælg en fil og klik på 'Ok'";
$contacts_import_text_group = "Vælg en gruppe og en fil. Klik på 'Ok'.";
$fbNoFile = "Filen blev ikke overført";
$fbPleaseWait = "Vent mens filen overføres...";

$strNotIncluded = "Importer ikke";
$contacts_import_feedback = "Følgende kolonner blev fundet i filen.<br />";
$contacts_import_feedback .= "Vælg den gruppe du vil importere til eller vælg at få grupperne oprettet automatisk på baggrund af kolonnerne i filen.<br />";
$contacts_import_feedback .= " Match sammenhængende Group-Office columns med kolonnerne fra filen. Vær sikker på du ikke har valgt en kolonne flere gange.";
$contacts_separator = "Værdier adskilt af";
$contacts_no_separator = "Du har ikke indtastet et separator tegn.";
$fbFilename = "Filnavn";
$contacts_import_title = "Importer adressebog";
$contacts_import_success = "Filen blev importeret";
$contacts_import_double = "Du har valgt en eller flere kolonner flere gange. Ret fejlen og prøv igen.";
$contacts_import_noname = 'Du skal vælge en navnefelt';
$contacts_import_incompatible = "Inkompatibelt filformat.<br /><br />Filen skal bestå af felter adskilt af komma.";
$strMember = "Medlem";
$contact_exist_warning = "<b>Note:</b> Denne bruger er allerede i kontaktpersons listen.";
$contacts_add_to_group = "Tilføj valgte brugere til kontaktpersonerne i gruppen...";
$contacts_add_to = "Tilføj valgte brugere til kontaktpersoner";
$contacts_add_user = "Tilføj";
$contacts_edit = "Ret";
$contacts_no_select = "Du har ikke valgt noget";
$contacts_this_contact = "Denne kontaktperson";

$contacts_seperator_text = 'Værdier adskilt af';
$contacts_quote = 'Værdier indsat i';
$contacts_clrf = 'Linier afsluttet af';
$contacts_auto_group = 'Opret automatisk grupper fra fil';
$contacts_import_to_group = 'Importer til gruppe';

//translation required
$contacts_search = 'search';
$cmdSearch = 'search';
$contacts_search_text = "Enter as search phrase and click on 'search'. You can use * as a wild character.";
$contacts_results = 'result(s)';


$contacts_color = 'Color';

$contacts_colors['black'] = 'Black';
$contacts_colors['red'] = 'Red';
$contacts_colors['green'] = 'Green';
$contacts_colors['blue'] = 'Blue';
$contacts_colors['pink'] = 'Pink';
$contacts_colors['orange'] = 'Orange';
$contacts_colors['brown'] = 'Brown';
?>
