<?php
require($GO_LANGUAGE->get_fallback_language_file('settings'));

$admin_properties = 'Egenskaper';
$admin_modules = 'Moduler';
$strPath = 'Sti';
$admin_invalid_path = 'Du har skrevet inn en ugyldig sti';
$admin_overview = 'Oversikt';
$admin_module = 'Modul';
$admin_modules_text = 'Velg de moduler du vil bruke og klikk på \''.$cmdSave.'\'.<br />Klikk på aktive moduler for å endre tillatelser.';
$admin_bookmarks_text = 'Opprett bokmerker her, som automatisk tilføyes når du oppretter en ny bruker.';
$admin_bookmark_new_window = 'Åpne bokmerke i nytt vindu';
$admin_menus_text = "Marker de(n) meny(er) som du vil bruke og klikk på 'Gjem'";
$admin_start_module = 'Start Group-Office i';
$admin_menus = "menyer";
$admin_formats = "datoformater";
$admin_date_formats_text = 'Tilføy datoformater i <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> med en beskrivelse og klikk på Ok.';
?>
