<?php
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Hai inserito l\'ora del periodo non valida';
$pm_add_hours_success = 'L\'evento è stato inserito con successo';
$pm_already_booked = 'Hai già impegni in questo periodo';
$pm_new_entry = 'Nuovo inserimento';
$pm_fees = 'Tariffe';
$pm_new_fee = 'Nuova tariffa';
$pm_users = 'Utenti';
$pm_materials = 'Materiali';
$pm_new_material = 'Nuovo materiale';
$pm_project_data = 'Dati progetto da';
$pm_load= 'Rapporti';
$pm_enter_data = 'Inserisci dati';
$pm_value = 'Valore';
$pm_too_old = 'Non ti è permesso inserire date più vecchie di una settimana';

$pm_employee = 'Impiegato';
$pm_project = 'Progetto';
$pm_starttime = 'Ora inizio';
$pm_endtime = 'Ora fine';
$pm_breaktime = 'Pausa';
$pm_this_week = 'Inserimenti della settimana';
$pm_no_projects = 'Non hai nessun progetto';
$pm_hours = 'Ore';
$pm_total_hours = 'Totale numero di ore';
$pm_client = 'Clienti';
$pm_created_at = 'Creato il';

$pm_show_all = 'Mostra tutto';
$pm_show_period = 'Mostra dal';
$pm_to = 'al';
$pm_show_month = 'Mostra mese';

$pm_total_hours_days = 'Totale numero di ore/giorni';
$pm_projects_count = 'progetto/i';
$pm_show_data = 'Mostra data';
$pm_new_project = 'Nuovo progetto';
$pm_other_contacts = 'Altri contatti';
$pm_no_contacts = 'Non hai contatti che possono fungere da cliente per questo progetto. E` necessario crearne uno prima.';

//translation required for 1.1
$pm_unit_value = 'Valore unità';
$pm_units = 'Unità';
$pm_mins = 'minuti';
$pm_no_fees = 'Nessuna spesa è stata creata. Solo un utente con privilegi di amministratore può creare delle spese.';
$pm_fee = 'Spese';
$pm_no_contact = 'Nessuno';
$pm_load_period= 'Periodo';
$pm_load_type= 'Carica dati per';
$pm_total_fee = 'Totale spese';
$pm_total_days = 'Totale giorni';
$pm_total_units = 'Totale unità';
$pm_summary = 'Sommario';

$pm_this_entry = 'questa prenotazione';
$pm_entry = 'prenota';


$pm_timer_started_at = 'Timer avviato alle';

$pm_start_timer = 'Avvia timer';

$pm_stop_timer = 'Ferma timer';



$pm_start_date = 'Data inizio';

$pm_end_date = 'End date';

$pm_responsible = 'Responsabile';

$pm_status = 'Stato';



$pm_status_values[-1] = 'Proposti';

$pm_status_values[0] = 'In corso';

$pm_status_values[101] = 'Completati';



$pm_filter = 'Filtro';

$pm_project_exists = 'Un progetto con questo nome esiste già';



$pm_alert = 'Questo progetto è scaduto';



$pm_budget = 'Budget';

$pm_probability = 'Probabilità';

$pm_yours_only = 'Solo miei';

$pm_description = 'Descrizione';



$pm_no_projects = 'Nessun progetto trovato.';

?>
