<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Khoảng thời gian bạn nhập không hợp lệ';
$pm_add_hours_success = 'Dữ liệu nhập đã được lưu thành công';
$pm_already_booked = 'Bạn đã được tính giờ trong khoảng thời gian này';
$pm_new_entry = 'New entry at';
$pm_fees = 'Chi phí';
$pm_new_fee = 'Chi phí mới';
$pm_users = 'Users';
$pm_materials = 'Materials';
$pm_new_material = 'New material';
$pm_project_data = 'Projectdata from';
$pm_load= 'Xem báo cáo';
$pm_enter_data = 'Enter data';
$pm_value = 'Giá trị';
$pm_too_old = 'Bạn không được phép nhập dữ liệu cũ hơn 01 tuần';

$pm_task = 'Công việc';

$pm_employee = 'Trưởng dự án';
$pm_project = 'Dự án';
$pm_starttime = 'Khởi điểm';
$pm_endtime = 'Kết thúc';
$pm_breaktime = 'Giờ nghỉ';
$pm_this_week = 'Entered this week';
$pm_no_projects = 'Bạn chưa có dự án nào';
$pm_hours = 'Giờ';
$pm_total_hours = 'Tổng số giờ';
$pm_client = 'Khách hàng';
$pm_created_at = 'Tạo lúc';

$pm_show_all = 'Xem toàn bộ';
$pm_show_period = 'Xem từ';
$pm_to = 'đến';
$pm_show_month = 'Xem tháng';

$pm_total_hours_days = 'Tổng số giờ/ngày';
$pm_projects_count = 'dự án';
$pm_show_data = 'Xem dữ liệu';
$pm_new_project = 'Tạo dự án mới';
$pm_other_contacts = 'Các liên hệ khác';
$pm_no_contacts = 'Bạn không có Liên hệ nào có thể là khách hàng cho dự án này. Hãy thêm thong tin liên hệ';

$pm_unit_value = 'Unit value';
$pm_units = 'Đơn vị';
$pm_mins = 'phút';
$pm_no_fees = 'There are no fees created yet. Only a user with administrator privileges can create fees.';
$pm_fee = 'Chi phí';
$pm_no_contact = 'None';
$pm_load_period= 'Khoảng thời gian';
$pm_load_type= 'Chỉ xem dữ liệu của';
$pm_total_fee = 'Tổng chi phí';
$pm_total_days = 'Tổng số ngày';
$pm_total_units = 'Tổng đơn vị thời gian';
$pm_summary = 'Tóm lược';
$pm_this_entry = 'bản ghi này';
$pm_entry = 'bản ghi';
//translation required
$pm_timer_started_at = 'Timer started at';
$pm_start_timer = 'Bắt đầu tính giờ';
$pm_stop_timer = 'Dừng tính giờ';

$pm_start_date = 'Ngày bắt đầu';
$pm_end_date = 'Ngày kết thúc';
$pm_responsible = 'Chịu trách nhiệm';
$pm_status = 'Trạng thái';
$pm_category = 'Loại dự án';
$pm_process_template = 'Quy trình chuẩn';
$pm_new_category = 'Tạo loại dự án mới';
$pm_new_template = 'Tạo quy trình mới';

$pm_days = 'ngày';
$pm_delay = 'Trễ';
$pm_remain = 'Còn';
$pm_advance = 'Sớm';
$pm_predict_delay = 'Ước đoán trễ';

$pm_status_values[0] = 'Đã huỷ';
$pm_status_values[1] = 'Khảo sát';
$pm_status_values[2] = 'Đã ký hợp đồng';
$pm_status_values[3] = 'Đang triển khai';
$pm_status_values[4] = 'Hoàn tất';

$pm_filter = 'Lọc theo';
$pm_project_exists = 'Tên dự án đã có';

$pm_clocked_in = 'Bạn đang được tính giờ. Nhấn vào đây nếu bạn muốn dừng';

$pm_alert = 'Dự án này đã quá hạn';
$pm_budget = 'Ngân sách';
$pm_probability = 'Khả năng trúng';
$pm_progress = 'Tiến trình';
$pm_yours_only = 'Chính mình';
$pm_description = 'Mô tả';

$pm_no_projects = 'Chưa có dự án nào.';

$pm_task_status_values[0] = 'Bỏ qua';
$pm_task_status_values[1] = 'Hoàn tất';
$pm_task_status_values[2] = 'Tiến hành';
$pm_task_status_values[3] = 'Chờ';
$pm_status_drop = 'Huỷ bỏ';
$pm_status_done = 'Hoàn tất';
$pm_status_begin = 'Bắt đầu';
$pm_status_running = 'Tiến hành';

$pm_task_order = '#';
$pm_task_name = 'Tên công việc';
$pm_task_person = 'Người thực hiện';
$pm_task_predecessors = 'Công việc<br>trước đó';
$pm_task_time = 'Số ngày';
$pm_task_status = 'Trạng thái';
$pm_task_approved = 'Duyệt';
$pm_task_document = 'Tài liệu';
$pm_task_level = 'Cấp';

$pm_task_duration = 'Thời gian';
$pm_task_planning = 'Dự kiến';
$pm_task_reality  = 'Thực tế';
$pm_task_advance  = 'Sớm';
$pm_task_latency  = 'Trễ';
$pm_task_start    = 'Bắt đầu';
$pm_task_stop     = 'Kết thúc';
$pm_task_days     = 'ngày';
$pm_task_day      = 'ngày';

$pm_task_comments = 'Chú thích';
$pm_task_new_comments = 'Thêm chú thích mới';
$pm_insert_task = 'Thêm công việc mới';
$pm_task_list_predecessors = 'Công việc trước đó';
$pm_move_task_up = 'Chuyển lên';
$pm_move_task_dn = 'Chuyển xuống';

$pm_legend_planning = 'Dự kiến';
$pm_legend_ongoing = 'Tiến hành';
$pm_legend_done = 'Hoàn tất';

$pm_legend_addtask = 'Thêm công việc mới';
$pm_legend_movetask = 'Thay đổi thứ tự công việc';
$pm_legend_deltask = 'Xoá công việc hoặc quy trình';

$cmdGantt = 'Biểu đồ Gantt';
$cmdDrop = 'Huỷ bỏ dự án';
$cmdRecover = 'Phục hồi dự án';

$pm_ConfirmDrop = 'Bạn có chắc chắn là bạn muốn huỷ bỏ dự án ?';
$pm_ConfirmRecover = 'Bạn có chắc chắn là bạn muốn phục hồi lại dự án ?';
$pm_ConfirmDeleteStatus = 'Bạn có chắc chắn là bạn muốn xoá trạng thái "%s"?';
$pm_ConfirmDeleteCategory = 'Bạn có chắc chắn là bạn muốn xoá loại dự án ';
$pm_ConfirmDeleteTemplate = 'Bạn có chắc chắn là bạn muốn xoá quy trình ';
$pm_DeleteCategory = 'Xoá';
$pm_CannotDelete = 'Không thể xoá loại dự án này vì có dự án đang dùng';
$pm_CategoryExists = "Đã có loại dự án '%s'";
$pm_EditCategory = 'Đổi tên loại dự án';
$pm_AddCategory = 'Thêm loại dự án mới:';
$pm_EditTemplate = 'Đổi tên quy trình mẫu';
$pm_AddTemplate = 'Thêm quy trình mẫu:';
$pm_TemplateExists = "Đã có quy trình mẫu '%s'";

$strReadRights = 'Giám sát';
$strWriteRights = 'Thành viên';
$acl_control_auth_groups = 'Nhóm tham gia';
$acl_control_auth_users = 'Người tham gia';

$strStatusChangeConfirm = 'Bạn đã thay đổi trạng thái công việc sang hoàn tất. Trưởng dự án sẽ được thông báo bằng email về thay đổi này. Bạn có chắc muốn thay đổi trạng thái công việc hay không?';
$mailTaskStatusChangedToDone  = '<html><body>Bạn được yêu cầu kiểm tra và duyệt một công việc đã hoàn tất:<br/><br/>Tên dự án: %s<br/>Mô tả dự án: %s<br/>Tên công việc: %s<br/><br/>Vui lòng nhấn <a href="%s">vào đây</a> hoặc vào phần quản lý dự án để biết thêm thông tin chi tiết.</body></html>';
$mailTaskStatusChangedToOngoing  = '<html><body>Một công việc thuộc trách nhiệm của bạn đã chuyển sang trạng thái %s:<br/><br/>Tên dự án: %s<br/>Mô tả dự án: %s<br/>Tên công việc: %s<br/>Số ngày: %s<br/><br/>Vui lòng nhấn <a href="%s">vào đây</a> hoặc vào phần quản lý dự án để biết thêm thông tin chi tiết.</body></html>';
$subjectTaskStatusChanged = '[Projects] Trạng thái công việc %s (dự án %s) đã chuyển sang %s';
$subjectTaskAssigneeChanged = '[Projects] Thay đổi người thực hiện công việc %s (dự án %s)';
//$strStatusChangeConfirm = ;
$mailTaskStatusChanged  = '<html><body>Công việc "<a href="%s">%s</a>" thuộc dự án "<a href="%s">%s</a>" đã thay đổi trạng thái từ %s sang %s.</body></html>';
$subjectTaskStatusChanged = '[Projects] Trạng thái công việc %s (dự án %s) đã thay đổi sang %s';
$mailTaskAssigneeLeft = '<html><body>Công việc bạn đang thực hiện đã được chuyển sang người khác: <br/><br/>Tên dự án: %s<br/>Mô tả dự án: %s<br/>Tên công việc: %s</body></html>';
$mailTaskAssigneeJoined = '<html><body>Bạn được chọn thực hiện một công việc: <br/><br/>Tên dự án: %s<br/>Mô tả dự án: %s<br/>Tên công việc: %s<br/>Days: %s<br/><br/>Vui lòng nhấn <a href="%s">vào đây</a> hoặc vào phần dự án để biết thêm thông tin chi tiết.</body></html>';
?>
