<?php
require($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'anotaчуo';
$no_notes_count = 'anotaчѕes';
$no_catagory = 'Categoria';
$no_no_notes = 'Nenhuma anotaчуo encontrada.';
$no_new_note = 'Nova anotaчуo';
$pm_note_exists = 'Jс existe uma note com este nome.';
$no_catagories = 'Categorias';
$no_no_catagories = 'Nуo existem categorias cadastradas.';
$no_new_catagory= 'Nova categoria';
$pm_catagory_exists = 'Esta categoria jс existe';
$no_catagories_count = 'Categorias';
$no_catagories_count_single = 'categoria';
$no_none = 'Nenhuma';
$no_responsible = 'Responsсvel';
$no_due_date = 'Data';

$no_project = 'Projeto';
$no_contact = 'Contato';
$no_file = 'Arquivo';

$no_show_all = 'Exibir todas';
$no_show_own = 'Exibir somente as minhas';
$no_show_responsible = 'Exibir por responsсvel';
?>