<?php
require($GO_LANGUAGE->get_fallback_base_language_file('groups'));

$groups_title = "Brugergrupper";
$groups_tab = "Grupper";
$groups_saved = "Indstillinger gemt.";
$groups_text = "Klik på en gruppe for at se egenskaberne.";
$groups_users_in = "Brugere i gruppen ";
$groups_no_contacts = "Du har ingen kontakter der kan vælges.<br /> Brug adressebogen til at tilføje kontakter.";

$add_group_text = "Indtast et navn og klik 'OK' for at oprette en ny gruppe.";
$add_group_fail = "Kunne ikke tilføje gruppen. Prøv igen.";
$add_group_success = "Gruppen er tilføjet.";
$add_group_exists = "Navnet findes allerede. Vælg et andet navn.";
$add_group_no_name = "Du har ikke angivet noget navn.";
$groups_everyone = "Denne gruppe er speciel og indeholder alle brugere. Den kan ikke ændres.";
$groups_users_in1 = "bruger(e) i gruppen";
$groups_no_users = "Der er ingen brugere i denne gruppe.";
$groups_users_in_select = "Vælg de brugere du vil tilføje gruppen:";
?>
