<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = 'Sumário do Sistema';
$si_hostname = 'Nome do Servidor';
$si_ip = 'Endereço IP';
$si_kernel = 'Versão de Kernel';
$si_web_server = 'Servidor Web';
$si_php_version = 'Versão de PHP';
$si_uptime = 'Tempo em Funcionamento';
$si_users = 'Usuários Atuais';
$si_average_load = 'Carga média';
$si_days = 'dias';
$si_hours = 'horas';
$si_mins = 'minutos';

$si_hardware_summary = 'Visão Geral do Hardware';
$si_processors = 'Processador(es)';
$si_model = 'Modelo';
$si_clock = 'Frequência do Processador';
$si_buffersize = 'Tamanho do Buffer';
$si_bogomips = 'Nível de Bogomips neste sistema';
$si_pci = 'Hdw tipo PCI';
$si_ide = 'Hdw tipo IDE';
$si_scsi = 'Hdw tipo SCSI';
$si_capacity = 'Capacidade';

$si_network_use = 'Uso da Rede';
$si_device = 'HDW';
$si_recieved = 'Recebido';
$si_sent = 'Enviado';
$si_error = 'Erro(s)';


$si_memory_use = 'Uso de Memória';
$si_type = 'Tipo';
$si_percentage_used = 'Porcentagem usada';
$si_free = 'Livre';
$si_used = 'Usada';
$si_size = 'Tamanho';
$si_physical = 'Memória Física';
$si_swap = 'Memória de swap';

$si_filesystems = 'Diretórios Montados';
$si_mount_point = 'Ponto da montagem';
$si_partition = 'Partições';
$si_total = 'Total';
$si_show_phpinfo = 'Configuração do PHP';
?>
