<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = 'Systemsammanställning';
$si_hostname = 'Hostnamn';
$si_ip = 'IP-adress';
$si_kernel = 'Kernelversion';
$si_web_server = 'Webbserver';
$si_php_version = 'PHPversion';
$si_uptime = 'Upptid';
$si_users = 'Inloggade användare';
$si_average_load = 'Snittbelastning';
$si_days = 'dagar';
$si_hours = 'timmar';
$si_mins = 'minuter';

$si_hardware_summary = 'Hårdvaruprofil';
$si_processors = 'Processorer';
$si_model = 'Modell';
$si_clock = 'Klockfrekvens';
$si_buffersize = 'Bufferstorlek';
$si_bogomips = 'System bogomips';
$si_pci = 'PCI-enheter';
$si_ide = 'IDE-enheter';
$si_scsi = 'SCSI-enheter';
$si_capacity = 'Kapacitet';

$si_network_use = 'Nätvärksanvädning';
$si_device = 'Enhet';
$si_recieved = 'Mottaget';
$si_sent = 'Skickat';
$si_error = 'Fel/Droppade';


$si_memory_use = 'Minnesanvändning';
$si_type = 'Typ';
$si_percentage_used = 'Procentuellt använt';
$si_free = 'Ledigt';
$si_used = 'Använt';
$si_size = 'Storlek';
$si_physical = 'Fysiskt minne';
$si_swap = 'Växlingsminne';

$si_filesystems = 'Monterade filsystem';
$si_mount_point = 'Monteringspunkter';
$si_partition = 'Partition';
$si_total = 'Total';
$si_show_phpinfo = 'PHP-konfiguration';
?>
