<?php
require($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Wilkommen in';
$sum_you_have = 'Sie haben';
$sum_new_messages = '<b>ungelesene</b> E-Mail-Nachrichten';
$sum_new_message = '<b>ungelesene</b> E-Mail-Nachricht';
$sum_no_new_mail = 'Keine ungelesenen E-Mails';

$sum_manage_announcements = 'Bekanntmachungen verwalten';
$sum_announcements_count = 'Bekanntmachungen';
$sum_announcements_count_single = 'Bekanntmachung';
$sum_no_announcements = 'Keine Bekanntmachungen vorhanden';
$sum_due_time = 'Anzeige bis';
$sum_new_announcement = 'Neue Bekanntmachung';
$sum_private = 'Privat';
?>
