<?php
require($GO_LANGUAGE->get_fallback_language_file('products'));

	$sc_amount = 'Tổng giá trị';
	$sc_add_category = 'Danh mục sản phẩm';
	$sc_add_attach_category = 'Danh mục Linh kiện';
	$sc_add_products = 'Sản phẩm mới';
	$sc_cart = 'Tạo bảng báo giá';
	$sc_order_list = 'Bảng giá';
	
	$sc_search_on = 'Tìm theo';
	$sc_search_phrase = 'Chứa cụm từ';
	$sc_in = 'trong';
	
	$sc_category_name = 'Tên danh mục';
	
	$sc_product_name = 'Tên sản phẩm';
	$sc_quantity = 'Số lượng';
	$sc_price = 'Giá tiền';
	$sc_total = 'Tổng cộng';
	$sc_inc_dec = 'Tăng/giảm';
	$sc_category = 'Danh mục';
	$sc_be_attachment = 'Là linh kiện';
	$sc_of = 'của';
	$sc_sum = 'Tổng giá tiền';
	$sc_inc_dec_quotation = 'Điều chỉnh giá';
	$sc_amount_quotation = 'Tổng giá trị bảng giá';
	$sc_information = 'Thông tin';
	$sc_part_number = 'Part number';
	$sc_image = 'Hình ảnh';
	$sc_VAT = 'VAT (%)';
	$sc_warranty = 'Chế độ bảo hành';
	$sc_cc = 'Cc';
	$sc_subject = 'Chủ đề';

	$sc_company = 'Đến';
	$sc_attn = 'Người nhận';
	$sc_fax = 'Fax';
	$sc_phone = 'Điện thoại';
	$sc_valid_date = 'Bảng giá có hiệu lực đến';
	
	$sc_order_number = 'Số hóa đơn';
	$sc_client = 'Khách hàng';
	$sc_employee = 'Nhân viên';
	$sc_delivery_place = 'Nơi giao hàng';
	$sc_delivery_date = 'Ngày giao hàng';
	$sc_sale_date = 'Ngày bán';
	$sc_pay_method = 'Phương thức thanh toán';
	
	$sc_fields['product_name'] = 'Tên';
	$sc_fields['description'] = 'Mô tả';
	$sc_fields['price'] = 'Giá tiền';

	$sc_fields['order_number'] = 'Số bảng báo giá';
	$sc_fields['sale_date'] = 'Ngày bán';
	$sc_fields['valid_date'] = 'Ngày hết hiệu lực';
	$sc_fields['company'] = 'Công ty';
	$sc_fields['attn'] = 'Người nhận';
	$sc_fields['cc'] = 'Đồng gửi';
	$sc_fields['phone'] = 'Điện thoại';
	$sc_fields['fax'] = 'Fax';
	$sc_fields['subject'] = 'Về việc';
	$sc_fields['seller'] = 'Người bán';

	$sc_all = '[TẤT CẢ]';
	$sc_top = '[ĐỨNG ĐẦU]';
	
	$sc_ChildOfItsself = 'Không thể tạo một danh mục là con của chính nó';
	$sc_Duplicate = '%s đã có, không thể thêm mới !';
	$sc_ConfirmDeleteCategory = 'Bạn có chắc chắn là muốn xóa danh mục \"%s\" và tất cả các danh mục con của nó ?';
	$sc_ConfirmDeleteCategory2 = 'Bạn có chắc chắn là muốn xóa danh mục \"%s\" ?';
	$sc_CannotDelete = 'Không thể xóa danh mục \"%s\" vì đã có sản phẩm trong danh mục này hoặc danh mục con của danh mục này';
	$sc_CannotDelete2 = 'Không thể xóa danh mục \"%s\" trong đã có sản phẩm trong danh mục này';
	
	$sc_ConfirmDeleteProduct = 'Bạn có chắc là muốn xóa mặt hàng \"%s\" ?';
	$sc_CannotDeleteProduct = 'Bạn không thể xóa mặt hàng \"%s\" vì đã có trong đơn đặt hàng';
	
	$sc_ConfirmDeleteOrder = 'Bạn có chắc là muốn xóa đơn đặt hàng \"%s\" ?';
	$sc_ConfirmDeleteProductFromCart = 'Bạn có chắc là muốn lấy mặt hàng \"%s\" ra khỏi giỏ hàng ?';
	
	$sc_AskInput = 'Xin vui lòng nhập';
	$sc_no_select = 'Không chọn';
	
	$sc_clear_cart = 'Xóa bảng báo giá';
	
	$sc_buy = 'Đưa vào bảng giá';
	$sc_buy_all = 'Đưa các món hàng đã chọn vào bảng giá';	
	$sc_export = 'Xuất';
?>
