<?php
require($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Vælg de brugere og grupper din konto skal være synlig for.";

//security
$security_text = "Indtast din adgangskode og de felter du vil ændre og klik på 'Gem'.";
$security_current_password = "Nuværende adgangskode";
$security_new_password = "Ny adgangskode";
$security_confirm_password = "Bekræft adgangskode";
$security_new_authcode = "Ny autorisationskode";
$security_confirm_authcode = "Bekræft autorisationskode";
$security_question = "Hemmeligt spørgsmål";
$security_answer = "Svar";
$security_wrong_password = "Forkert adgangskode.";
$security_tasks = "Handling udført";
$security_password_update = "Adgangskode opdateret.";
$security_authcode_update = "Autorisationskode opdateret.";
$security_question_update = "Spørgsmål og svar opdateret.";
$security_question_fail = "Du skal indtaste både spørgsmål og svar.";

$acProfile = "Profil";
$acSecurity = "Sikkerhed";
$acPrivacy = "Personlig beskyttelse";
$acManager = "Din konto";
$acStatistics = "Statistik";
$acProfileText = "Klik på 'Gem' for at gemme din profil. Felterne markeret med * skal udfyldes.";
$acTitle = "Din konto";
$ac_login_info = "Login information";
$ac_registration_time = "Oprettelsestidspunkt";
$ac_lastlogin = "Sidste login";
$ac_logins = "Totalt antal logins";
$ac_disk_usage = "Disk forbrug";
$ac_max_diskspace = "Total diskplads";
$ac_available_diskspace = "Tilgængelig diskplads";
$ac_used_diskspace = "Forbrugt diskplads";
$ac_used = "brugt";
?>
