<?php
require($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Seleccione los usuarios y grupos para  quienes quiere ser visible.";

//security
$security_text = "Ingrese su clave y los campos que usted desea cambiar y haga click en 'grabar'.";
$security_current_password = "Clave Actual";
$security_new_password = "Nueva Clave";
$security_confirm_password = "Confirme Clave";
$security_new_authcode = "Nuevo c&oacute;digo de autorizaci&oacute;n";
$security_confirm_authcode = "Confirme c&oacute;digo de autorizaci&oacute;n";
$security_question = "Pregunta Secreta";
$security_answer = "Respuesta";
$security_wrong_password = "Clave equivocada.";
$security_tasks = "Tareas completadas";
$security_password_update = "Claves actualizadas.";
$security_authcode_update = "C&oacute;digos de autorizaci&oacute;n actualizados.";
$security_question_update = "Pregunta y respuesta actualizadas.";
$security_question_fail = "Usted no ingres&oacute; la pregunta y la respuesta.";

$acProfile = "Perfil";
$acSecurity = "Seguridad";
$acPrivacy = "Privacidad";
$acManager = "Su cuenta";
$acStatistics = "Estad&iacute;sticas";
$acProfileText = "Haga click en 'grabar' para cambiar su cuenta. Los campos marcados con * son obligatorios.";
$acTitle = "Su cuenta";
$ac_login_info = "Informaci&oacute;n de Ingreso";
$ac_registration_time = "Hora de registro";
$ac_lastlogin = "Ultimo ingreso";
$ac_logins = "Total de ingresos";
$ac_disk_usage = "Uso del disco";
$ac_max_diskspace = "M&aacute;ximo espacio en disco";
$ac_available_diskspace = "Espacio disponible";
$ac_used_diskspace = "Espacio en disco usado";
$ac_used = "usado";
$ac_add_user = "Autorizacion Requerida";
$ac_auth_error = "Ha ocurrido un error mientras se autorizaba.  FAvor trate nuevamente.";
$ac_auth_success = "Su cuenta esta visible ahora para este usuario y un mensaje ha sido enviado a ese usuario aceptando su requermiento.";
$ac_auth_decline = "Un mesaje ha sido enviado a ese usuario declinando su requerimeinto.";
$ac_auth_accept_mail_title = "Requerimiento de autorizacion de Group-Office aceptado";
$ac_auth_decline_mail_title = "Requerimiento de autorizacion de Group-Office denegado";
$ac_salutation = "Respetado Senor(a)";
$ac_auth_accept_mail_body = "ha sido aceptado su requerimiento de hacer visible la cuenta para usted.";
$ac_auth_decline_mail_body = "no ha sido aceptado su requerimiento de hacer visible la cuenta para usted.";
$ac_request_auth = "requiere usted haga su cuenta visible para el. Desea hacer su cuenta visible para este usuario?";
$ac_request_auth_mail_title ="Requerimiento de autorizacion de Group-Office";
$ac_invalid_email = "La direccion de correo electronica que ha digitado no esta registrada en el sistema. Por favor trate nuevamente.";
$ac_request_mail_body_prefix = "Un mensaje ha sido enviado a ";
$ac_request_mail_body_suffix = "requiriendo hacer visible la cuenta para Usted.";
$ac_auth_text = "Entre la direccion de correo del usuario que desea hacerse visible.";
$ac_accept = "Aceptar";
$ac_decline = "No aceptar";
?>
