<?php
require($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Välj de användare och grupper du vill vara synlig för.";

//security
$security_text = "Skriv in ditt lösenord och de fält du vill ändra på, tryck sedan 'Spara'.";
$security_current_password = "Nuvarande lösenord";
$security_new_password = "Nytt lösenord";
$security_confirm_password = "Bekräfta lösenord";
$security_new_authcode = "Ny authoriseringskod";
$security_confirm_authcode = "Bekräfta authoriseringskod";
$security_question = "Hemlig fråga";
$security_answer = "Svar";
$security_wrong_password = "Felaktigt lösenord.";
$security_tasks = "Uppgift slutförd";
$security_password_update = "Lösenord uppdaterat.";
$security_authcode_update = "Authoriseringskoder uppdaterade.";
$security_question_update = "Fråga och svar uppdaterat.";
$security_question_fail = "Du fyllde inte i både frågan och svaret.";

$acProfile = "Profil";
$acSecurity = "Säkerhet";
$acPrivacy = "Privat";
$acManager = "Ditt konto";
$acStatistics = "Statistik";
$acProfileText = "Tryck på 'Spara' för att ändra din profil. Fält markerade med * måste fyllas i.";
$acTitle = "Ditt konto";
$ac_login_info = "Kontoinformation";
$ac_registration_time = "Registreringstid";
$ac_lastlogin = "Senast inloggad";
$ac_logins = "Antal inloggningar";
$ac_disk_usage = "Använt utrymme";
$ac_max_diskspace = "Max utrymme";
$ac_available_diskspace = "Tillgängligt utrymme";
$ac_used_diskspace = "Använt utrymme";
$ac_used = "använt";
?>
