<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Chọn người hoặc nhóm người mà bạn muốn cho xem.";

//security
$security_text = "Nhập mật khẩu và các thông tin bạn muốn thay đổi sau đó nhấn vào 'Đồng ý' hoặc 'Áp dụng'.";
$security_current_password = "Mật khẩu hiện tại";
$security_new_password = "Mật khẩu mới";
$security_confirm_password = "Xác nhận mật khẩu";
$security_new_authcode = "Mã xác thực mới";
$security_confirm_authcode = "Xác nhận mã xác thực";
$security_question = "Câu hỏi gợi nhớ";
$security_answer = "Trả lời";
$security_wrong_password = "Sai mật khẩu.";
$security_tasks = "Công việc đã kết thúc";
$security_password_update = "Đã cập nhật mật khẩu.";
$security_authcode_update = "Đã cập nhật mã xác thực.";
$security_question_update = "Đã cập nhật câu hỏi gợi nhớ và câu trả lời.";
$security_question_fail = "Bạn nhập không đủ câu hỏi gợi nhớ và câu trả lời.";

$acProfile = "Hồ sơ cá nhân";
$acSecurity = "Bảo mật";
$acPrivacy = "Cá nhân";
$acManager = "Tài khoản của bạn";
$acStatistics = "Thống kê";
$acProfileText = "Nhấn vào 'Lưu' để thay đổi thông tin. Cần nhập đầy đủ các vùng có dấu *.";
$acTitle = "Tài khoản của bạn";
$ac_login_info = "Thông tin đăng nhập";
$ac_registration_time = "Thời điểm đăng ký";
$ac_lastlogin = "Lần đăng nhập cuối cùng";
$ac_logins = "Tổng số lần đăng nhập";
$ac_disk_usage = "Việc sư dụng đĩa";
$ac_max_diskspace = "Dung lượng tối đa";
$ac_available_diskspace = "Vùng đĩa trống";
$ac_used_diskspace = "Vùng đĩa đã dùng";
$ac_used = "đã dùng";

//translation required
$ac_add_user = 'Yêu cầu xác thực';
$ac_auth_error = 'Lỗi khi thực hiện xác thực. Xin thử lại.';
$ac_auth_success = 'Người này đã có thể thấy được tài khoản của bạn và 1 thông báo đã được gửi đến người đó cho biết bạn đã chấp nhận yêu cầu.';
$ac_auth_decline = 'Thông báo đã được gửi đến người này cho biết bạn từ chối yêu cầu.';
$ac_auth_accept_mail_title = 'Group-Office yêu cầu xác thực được chấp thuận';
$ac_auth_decline_mail_title = 'Group-Office yêu cầu xác thực bị từ chối';

$ac_auth_accept_mail_body = 'Tài khoản có thể xem được theo yêu cầu của bạn.';
$ac_auth_decline_mail_body = 'has declined your request to make his account visible to you.';
$ac_request_auth = 'requests your permission to make your account visible. Do you want to make your account visible to this user?';
$ac_request_auth_mail_title ='Group-Office yêu cầu xác thực';
$ac_invalid_email = 'Địa chỉ e-mail mà bạn nhập chưa có trong hệ thống. Xin nhập lại.';
$ac_request_mail_body_prefix = 'Thông báo đã được gửi đến ';
$ac_request_mail_body_suffix = 'yêu cầu xin phép được xem thông tin tài khoản.';
$ac_auth_text = 'Nhập địa chỉ e-mail của người mà bạn muốn xem tài khoản.';

$ac_accept = 'Chấp nhận';
$ac_decline = 'Từ chối';
$ac_salutation = 'Chào';
?>
