    <img <?php echo $evstr ?> class="toolbaritem_flat" name="incr_colspan" 
    	onclick="if (<?php echo 'ktml_'.$objectName; ?>.toolbar.checkHelp(this, event)) { <?php echo 'ktml_'.$objectName; ?>.toolbar.showHelp('buttons', './', 'modules/tableedit'); } else { mergeRight(ktml_<?php echo $objectName ?>); }"  
    	src="<?php echo $dirDepth ?>includes/ktedit/modules/tableedit/images/increasecolspan.gif" 
    	width="22" 
    	height="22" 
    	kttype="btn"
    	title="<?php echo (isset($KT_Messages["Increase Colspan"]))? $KT_Messages["Increase Colspan"] : "Increase Colspan"; ?>"		
    	alt="<?php echo (isset($KT_Messages["Increase Colspan"]))? $KT_Messages["Increase Colspan"] : "Increase Colspan"; ?>"
    	border="0"/>
    <img <?php echo $evstr ?>  class="toolbaritem_flat" name="incr_rowspan" 
    	onclick="if (<?php echo 'ktml_'.$objectName; ?>.toolbar.checkHelp(this, event)) { <?php echo 'ktml_'.$objectName; ?>.toolbar.showHelp('buttons', './', 'modules/tableedit'); } else { mergeDown(ktml_<?php echo $objectName ?>); }"  
    	src="<?php echo $dirDepth ?>includes/ktedit/modules/tableedit/images/increaserowspan.gif" 
    	width="22" 
    	height="22" 
    	kttype="btn"
    	title="<?php echo (isset($KT_Messages["Increase Rowspan"]))? $KT_Messages["Increase Rowspan"] : "Increase Rowspan"; ?>"							
    	alt="<?php echo (isset($KT_Messages["Increase Rowspan"]))? $KT_Messages["Increase Rowspan"] : "Increase Rowspan"; ?>"
    	border="0"/>
    <img <?php echo $evstr ?>  class="toolbaritem_flat" name="add_col" 
    	onclick="if (<?php echo 'ktml_'.$objectName; ?>.toolbar.checkHelp(this, event)) { <?php echo 'ktml_'.$objectName; ?>.toolbar.showHelp('buttons', './', 'modules/tableedit'); } else { processColumn('add', ktml_<?php echo $objectName ?>); }"  
    	src="<?php echo $dirDepth ?>includes/ktedit/modules/tableedit/images/addcol.gif" 
    	width="22" 
    	height="22" 
    	kttype="btn"
    	title="<?php echo (isset($KT_Messages["Add Column"]))? $KT_Messages["Add Column"] : "Add Column"; ?>"
    	alt="<?php echo (isset($KT_Messages["Add Column"]))? $KT_Messages["Add Column"] : "Add Column"; ?>"
    	border="0"/>
    <img <?php echo $evstr ?>  class="toolbaritem_flat" name="add_row" 
    	onclick="if (<?php echo 'ktml_'.$objectName; ?>.toolbar.checkHelp(this, event)) { <?php echo 'ktml_'.$objectName; ?>.toolbar.showHelp('buttons', './', 'modules/tableedit'); } else { processRow('add', ktml_<?php echo $objectName ?>); }"  
    	src="<?php echo $dirDepth ?>includes/ktedit/modules/tableedit/images/addrow.gif" 
    	width="22" 
    	height="22" 
    	kttype="btn"
    	title="<?php echo (isset($KT_Messages["Add Row"]))? $KT_Messages["Add Row"] : "Add Row"; ?>"
    	alt="<?php echo (isset($KT_Messages["Add Row"]))? $KT_Messages["Add Row"] : "Add Row"; ?>"
    	border="0"/>
    <br/>
    <img <?php echo $evstr ?>  class="toolbaritem_flat" name="rmv_colspan" 
    	onclick="if (<?php echo 'ktml_'.$objectName; ?>.toolbar.checkHelp(this, event)) { <?php echo 'ktml_'.$objectName; ?>.toolbar.showHelp('buttons', './', 'modules/tableedit'); } else { splitCell(ktml_<?php echo $objectName ?>); }"  
    	src="<?php echo $dirDepth ?>includes/ktedit/modules/tableedit/images/decreasecolspan.gif" 
    	width="22" 
    	height="22" 
    	kttype="btn"
    	alt="<?php echo (isset($KT_Messages["Decrease Colspan"]))? $KT_Messages["Decrease Colspan"] : "Decrease Colspan"; ?>"
    	title="<?php echo (isset($KT_Messages["Decrease Colspan"]))? $KT_Messages["Decrease Colspan"] : "Decrease Colspan"; ?>"/>
    <img <?php echo $evstr ?>  class="toolbaritem_flat" name="rmv_rowspan" 
    	onclick="if (<?php echo 'ktml_'.$objectName; ?>.toolbar.checkHelp(this, event)) { <?php echo 'ktml_'.$objectName; ?>.toolbar.showHelp('buttons', './', 'modules/tableedit'); } else { unMergeDown(ktml_<?php echo $objectName ?>); }"  
    	src="<?php echo $dirDepth ?>includes/ktedit/modules/tableedit/images/decreaserowspan.gif" 
    	width="22" 
    	height="22" 
    	kttype="btn"
    	title="<?php echo (isset($KT_Messages["Decrease Rowspan"]))? $KT_Messages["Decrease Rowspan"] : "Decrease Rowspan"; ?>"
    	alt="<?php echo (isset($KT_Messages["Decrease Rowspan"]))? $KT_Messages["Decrease Rowspan"] : "Decrease Rowspan"; ?>"/>
    <img <?php echo $evstr ?>  class="toolbaritem_flat" 
    	name="rmv_col" 
    	onclick="if (<?php echo 'ktml_'.$objectName; ?>.toolbar.checkHelp(this, event)) { <?php echo 'ktml_'.$objectName; ?>.toolbar.showHelp('buttons', './', 'modules/tableedit'); } else { processColumn('remove', ktml_<?php echo $objectName ?>); }"  
    	src="<?php echo $dirDepth ?>includes/ktedit/modules/tableedit/images/removecol.gif" 
    	width="22" 
    	height="22" 
    	kttype="btn"
    	title="<?php echo (isset($KT_Messages["Remove Column"]))? $KT_Messages["Remove Column"] : "Remove Column"; ?>"
    	alt="<?php echo (isset($KT_Messages["Remove Column"]))? $KT_Messages["Remove Column"] : "Remove Column"; ?>"
    	border="0"/>
    <img <?php echo $evstr ?> class="toolbaritem_flat" 
    	name="rmv_row" 
    	onclick="if (<?php echo 'ktml_'.$objectName; ?>.toolbar.checkHelp(this, event)) { <?php echo 'ktml_'.$objectName; ?>.toolbar.showHelp('buttons', './', 'modules/tableedit'); } else { processRow('remove', ktml_<?php echo $objectName ?>); }"  
    	src="<?php echo $dirDepth ?>includes/ktedit/modules/tableedit/images/removerow.gif" 
    	width="22" 
    	height="22" 
    	title="<?php echo (isset($KT_Messages["Remove Row"]))? $KT_Messages["Remove Row"] : "Remove Row"; ?>"
    	alt="<?php echo (isset($KT_Messages["Remove Row"]))? $KT_Messages["Remove Row"] : "Remove Row"; ?>"
    	kttype="btn"
    	border="0"/>
    <!--<br/>-->
