<?php
require($GO_LANGUAGE->get_fallback_language_file('email'));

//Email
$ml_from = "Från";
$ml_to = "Till";
$ml_send = "Sänd";
$ml_attach = "Bifoga";
$ml_attachments = "Bifogningar";
$ml_attachment = "Bifogning";
$ml_high = "Hög";
$ml_normal = "Normal";
$ml_low = "Låg";
$ml_priority = "Prioritet";
$ml_subject = "Ämne";
$ml_filename = "Filnamn";
$ml_total_size = "Total storlek";
$ml_size = "Storlek";
$ml_to_empty = "Du angav ingen mottagare.";
$ml_print = "Skriv ut";
$fbNoSelect = "Du valde inget meddelande";

$ml_inbox = 'inkorg';
$ml_properties = 'egenskaper';
$ml_add_account = "Lägg till e-postkonto";
$em_new_folder = "Ny folder";
$ml_your_accounts = "Dina e-postkonton";
$ml_no_accounts = "Du har inga e-postkonton konfigurerade.";
$ml_original_follows = "----- Ursprungligt Meddelande -----";
$ml_welcome = "Välkommen till Group-Office E-post";
$ml_text = "Tryck på konton för att lägga till ett e-postkonto.";
$ml_accounts = "konton";
$ml_compose = "skriv";
$ml_delete = "radera";
$ml_refresh = "ladda om";
$ml_reply = "svara";
$ml_forward = "skicka vidare";
$ml_reply_all = "svara till alla";
$ml_delete_message = "Är du säker på att vill radera detta meddelande permanent?";
$ml_no_subject = "Inget subjekt";
$ml_no_reciepent = "Undisclosed reciepent";
$ml_online_files = "direktkopplade filer";
$ml_send_error = "Misslyckades med att skicka brevet.";

$ml_attach_forget = "Du har valt en fil men inte bifogat den.";
$ml_messages = "meddelande(n)";
$ml_message = 'detta meddelande';
$ml_messages2 = 'meddelanden';
$ml_new = "ny";
$ml_delete_mailbox = "Är du säker på att vill radera markerade meddelanden permanent?";

$contact_profile = "Kontaktprofil";
$ml_add_contact = "Lägg till sändare till kontakter";
$strHost = "Host";
$strDefault = "Default";
$ml_edit_account = "Editera konto";
$ml_new_account = "Nytt konto";
$ml_no_messages = "Det är inga meddelande i denna folder.";
$ml_file_too_big = "Filen du försökte bifoga är för stor. Maximala storleken för bifogade filer är inställt till: ";
$fbNoRightToOverwrite = "Filen existerar redan, och du har inte rättigheter att skriva över den.";
$ml_save_attachment = "Spara bifogningen i Group-Office.";
$ml_folders = "foldrar";

$ml_select_folder = "Välj den folder där Group-Office kan lagra skickad post eller ange ett namn nedan för att skapa en folder";
$ml_connect_failed = "Misslyckades att skapa en anslutning till e-postservern:";
$ml_at_port = "port";
$ml_solve_error = 'Tryck på \'Konton\' för att återgärda dina kontoinställningar eller tryck på \'Ladda om\' för att öppna upp standardkonton.';
$ml_sent_items = "Skickade saker";
$ml_spam = "Spam";
$ml_use = "Använd";
$ml_synchronise = "synkronisera";
$ml_move_mail = "Flytta valda meddelande till folder...";
$ml_filters = "filter";
$ml_move_to = "flytta sedan meddelandet till folder: ";
$ml_email_is = "Ifall avsändarens e-postadress innehåller:";
$ml_to_is = "Ifall mottagarens fält innehåller:";
$ml_cc_is = "Ifall cc-fältet innehåller:";

$ml_subject_is = "Ifall subjektet innehåller:";
$ml_new_filter = "Nytt filter:";
$ml_field = "Fält";
$ml_contains = "Innehållet";
$ml_folder = "Folder";
$ml_no_folders = "Du har inga foldrar så du kan inte skapa några filter.";
$ml_unwanted = "Klicka här ifall e-post från denna avsändare är oönskad";
$fbFolderSize = "Storlek av folder";
$ml_move_up = "Öka prioritet";
$ml_delete_filter = "Är du säker på att du vill radera detta filter?";
$ml_high_priority = "Detta meddelande har hög prioritet!";
$ml_low_priority = "Detta meddelande har låg prioritet.";
$ml_block = "blocka avsändare";
$ml_sent_items_fail = "Meddelandet har skickats, men det uppstod fel när meddelandet skulle skapas i din ut-folder. Kontrollera ditt IMAP-konto.";
$fbProperties = "egenskaper";
$ml_notification = "Begär mottagaren att skicka en notifikation när brevet är läst";
$ml_ask_notify = "Avsändaren av detta meddelande har begärt en notifikation av dig när brevet är läst. Vill du skicka denna?";
$ml_displayed = "Följande e-post har visats för ";
$ml_notify = "Läsnotifikation";
$ml_delete_filter1 = "Radera filter";
$ml_html_message_attached = "Original HTML-meddelande är bifogat";
$ml_add_recievers = "Lägg till okända mottagare till din adressbok";
$ml_no_folders = 'Du har inga foldrar att filtrera till';
$ml_no_filters = 'Du har inga filter';
$ml_host = 'Host';
$ml_port = 'Port';
$ml_type = 'Typ';
$ml_servertype = 'Servertyp';
$ml_format = 'Format';
$ml_loose_changes = 'Ändringar kommer att gå förlorade. Är du säker?';
$ml_markread = "marker som läst";
$ml_markunread = "markera som oläst";
$ml_root_mailbox = "toppmailbox";
$ml_inside = "in";

$ml_no_mailbox = "Detta är ingen epostlåda. Denna folder kan ej innehålla meddelanden.";
$ml_signature = 'Signatur';

$ml_root = 'Huvudbrevlåda';
?>
