<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$ft_title = "Loại hồ sơ";
$ft_text = "Loại hồ sơ được tự động thêm vào bởi HPT-OBM. Bạn có thể thay đổi biểu tượng và tên tại đây.";

$ft_icon = "Biểu tượng";
$ft_extension = "Phần mở rộng";
$ft_friendly = "Tên thân thiện";
$ft_content = "Loại nội dung";
$ft_no_filetypes = "Không tìm thấy loại nào.";
$ft_upload_text = "Chọn loại hồ sơ để đưa vào. Chỉ được dùng định dạng GIF.";
$ft_no_file = "Không nhận được hồ sơ nào.";
$ft_please_wait = "Xin đợi trong giây lát, đang đưa biểu tượng vào...";
$ft_properties = "Đặc tính";
$ft_filename = "Tên hồ sơ";
$ft_current_icon = "Biểu tượng hiện tại";
?>
