<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = 'System oversigt';
$si_hostname = 'Server navn';
$si_ip = 'IP addresse';
$si_kernel = 'Kerne version';
$si_web_server = 'Web server';
$si_php_version = 'PHP version';
$si_uptime = 'Oppetid';
$si_users = 'Aktuelt antal brugere';
$si_average_load = 'Gennemsnitlig belastning';
$si_days = 'dage';
$si_hours = 'timer';
$si_mins = 'minutter';

$si_hardware_summary = 'Hardware oversigt';
$si_processors = 'Processorer';
$si_model = 'Model';
$si_clock = 'Klok frekvens';
$si_buffersize = 'Buffer størrelse';
$si_bogomips = 'System bogomips';
$si_pci = 'PCI enheder';
$si_ide = 'IDE enheder';
$si_scsi = 'SCSI enheder';
$si_capacity = 'Kapacitet';

$si_network_use = 'Netværk belastning';
$si_device = 'Enhed';
$si_recieved = 'Modtaget';
$si_sent = 'Sendt';
$si_error = 'Fejl/tab';


$si_memory_use = 'Hukommelsesforbrug';
$si_type = 'Type';
$si_percentage_used = 'Procent brugt ';
$si_free = 'Fri';
$si_used = 'Brugt';
$si_size = 'Total';
$si_physical = 'Fysisk hukommelse';
$si_swap = 'Virtuel hukommelse';

$si_filesystems = 'Filsystemer';
$si_mount_point = 'Mount point';
$si_partition = 'Partition';
$si_total = 'Total';
$si_show_phpinfo = 'PHP konfiguration';
?>
