<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));
$si_system_summary = 'Résumé du système';
$si_hostname = 'Nom d\'hôte';
$si_ip = 'adresse IP';
$si_kernel = 'version du noyau';
$si_web_server = 'Serveur Web';
$si_php_version = 'Version de PHP';
$si_uptime = 'Temps de fonctionnement';
$si_users = 'Utilisateurs courants';
$si_average_load = 'Charge moyenne';
$si_days = 'jours';
$si_hours = 'heures';
$si_mins = 'minutes';

$si_hardware_summary = 'Informations sur le matériel';
$si_processors = 'Processeurs';
$si_model = 'Modèle';
$si_clock = 'Fréquence d\'horloge';
$si_buffersize = 'Taille du buffer';
$si_bogomips = 'Système bogomips';
$si_pci = 'Périphériques PCI';
$si_ide = 'Périphériques IDE';
$si_scsi = 'Périphériques SCSI';
$si_capacity = 'Capacité';

$si_network_use = 'Utilisation du réseau';
$si_device = 'Périphérique';
$si_recieved = 'Recus';
$si_sent = 'Envoyés';
$si_error = 'Erreur/Baisse';


$si_memory_use = 'Utilisation de la mémoire';
$si_type = 'Type';
$si_percentage_used = 'Pourcentage utilisé';
$si_free = 'Libre';
$si_used = 'Utilisé';
$si_size = 'Taille';
$si_physical = 'Mémoire physique';
$si_swap = 'Mémoire d\'échange';

$si_filesystems = 'Systèmes de fichiers montés';
$si_mount_point = 'Point de montage';
$si_partition = 'Partition';
$si_total = 'Total';
$si_show_phpinfo = 'Configuration PHP';
?>