<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$si_system_summary = 'Sistema';
$si_hostname = 'Nome computer';
$si_ip = 'Indirizzo IP';
$si_kernel = 'Versione Kernel';
$si_web_server = 'Server Web';
$si_php_version = 'Versione PHP';
$si_uptime = 'Uptime';
$si_users = 'Utenti connessi';
$si_average_load = 'Carico medio';
$si_days = 'giorni';
$si_hours = 'ore';
$si_mins = 'minuti';

$si_hardware_summary = 'Caratteristiche Hardware';
$si_processors = 'Processori';
$si_model = 'Modello';
$si_clock = 'Frequenza di Clock';
$si_buffersize = 'Dimensione Buffer';
$si_bogomips = 'Bogomips del sistema';
$si_pci = 'Periferiche PCI';
$si_ide = 'Dischi IDE';
$si_scsi = 'Dischi SCSI';
$si_capacity = 'Capacità';

$si_network_use = 'Utilizzo Rete';
$si_device = 'Periferica';
$si_recieved = 'Recevuto';
$si_sent = 'Inviato';
$si_error = 'Err/Drop';


$si_memory_use = 'Utilizzo Memoria';
$si_type = 'Tipo';
$si_percentage_used = 'Percentuale di utilizzo';
$si_free = 'Libero';
$si_used = 'Utilizzato';
$si_size = 'Dimensione';
$si_physical = 'Memoria fisica';
$si_swap = 'Memoria Swap';

$si_filesystems = 'Filesystem';
$si_mount_point = 'Mount point';
$si_partition = 'Partizione';
$si_total = 'Totale';
$si_show_phpinfo = 'Configurazione PHP';
?>
