<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'Аксесоари';
$admin_modules = 'Модули';
$strPath = 'Път';
$admin_invalid_path = 'Въвели сте невалидна насока';
$admin_overview = 'Виж отново';
$admin_module = 'Модул';
$admin_modules_text = 'Изберете модулите които искате да използвате и натиснете \''.$cmdSave.'\'.<br />Натиснете върху активните модули зада промените техните разрешения.';
$admin_bookmarks_text = 'Добавете лента за отбелязване тук която автоматично ще бъде създадена когато регистрирате нов потребител.';
$admin_bookmark_new_window = 'Отворете лентата за отбелязване в нов прозорец';
$admin_menus_text = "Проверете менютата които желаете да използвате и натиснете 'запази'";
$admin_start_module = 'Стартирай Group-Office в';
$admin_menus = "Меню";
$admin_formats = "Дата формат";
$admin_date_formats_text = 'Добавете дата форматите в <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> с описание и натиснете Ok.';
?>
