<?php
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Språk";
$pref_theme = "Tema";
$pref_date_format = "Datumformat";
$pref_thousands_seperator = "Tusentalsseparator";
$pref_decimal_seperator = "Decimalseperator";
$pref_mail_client = "Använd Group-Office e-postklient för att skicka e-post.";
$pref_look = "Känsla & utseende";
$pref_notations = "Notations";
$pref_currency = 'Valuta';
$pref_currency = 'Valuta';
$pref_region_code = 'Region';
$pref_max_rows_list = 'Maximalt antal rader i listor';
?>
