<?php
	$sc_amount = 'Amount';
	$sc_add_category = 'Product category';
	$sc_add_attach_category = 'Accessories category';
	$sc_add_products = 'New product';
	$sc_cart = 'Create a quotation';
	$sc_order_list = 'Quotations';
	
	$sc_search_on = 'Search on';
	$sc_search_phrase = 'Phrase';
	$sc_in = 'in';
	
	$sc_category_name = 'Category name';
	
	$sc_product_name = 'Product name';
	$sc_quantity = 'Quantity';
	$sc_price = 'Price';
	$sc_total = 'Total';
	$sc_inc_dec = 'Inc/Dec';
	$sc_category = 'Category';
	$sc_be_attachment = 'is accessory';
	$sc_of = 'of';
	$sc_sum = 'Amount';
	$sc_inc_dec_quotation = 'Price adjustment';
	$sc_amount_quotation = 'Quotation amount';	
	$sc_information = 'Information';
	$sc_part_number = 'Part number';
	$sc_image = 'Image';
	$sc_VAT = 'VAT (%)';
	$sc_warranty = 'Warranty';
	$sc_cc = 'Cc';
	$sc_subject = 'Subject';

	$sc_company = 'To';
	$sc_attn = 'Attn.';
	$sc_fax = 'Fax';
	$sc_phone = 'Phone';
	$sc_valid_date = 'Quotation valid until';
	
	$sc_order_number = 'Quotation number';
	$sc_client = 'Client';
	$sc_employee = 'Saleman';
	$sc_delivery_place = 'Nơi giao hàng';
	$sc_delivery_date = 'Ngày giao hàng';
	$sc_sale_date = 'Effective';
	$sc_pay_method = 'Phương thức thanh toán';
	
	$sc_fields['product_name'] = 'Name';
	$sc_fields['description'] = 'Description';
	$sc_fields['price'] = 'Price';

	$sc_fields['order_number'] = 'Quotation number';
	$sc_fields['sale_date'] = 'Effective';
	$sc_fields['valid_date'] = 'Quotation valid until';
	$sc_fields['company'] = 'To';
	$sc_fields['attn'] = 'Attn.';
	$sc_fields['cc'] = 'Cc';
	$sc_fields['phone'] = 'Phone';
	$sc_fields['fax'] = 'Fax';
	$sc_fields['subject'] = 'Subject';
	$sc_fields['seller'] = 'Saleman';

	$sc_all = '[ALL]';
	$sc_top = '[TOP]';
	
	$sc_ChildOfItsself = 'A category can not be child category of itself';
	$sc_Duplicate = '%s already exists, can not add a new !';
	$sc_ConfirmDeleteCategory = 'Are you sure you want to delete \"%s\" category and its all child categories ?';
	$sc_ConfirmDeleteCategory2 = 'Are you sure you want to delete \"%s\" category ?';
	$sc_CannotDelete = 'Can not delete \"%s\" category because there are product in this category or in its child categories';
	$sc_CannotDelete2 = 'Can not delete \"%s\" category because there are product in this category ';
	
	$sc_ConfirmDeleteProduct = 'Are you sure you want to delete \"%s\" product ?';
	$sc_CannotDeleteProduct = 'Can not delete \"%s\" product because it was in quotation';
	
	$sc_ConfirmDeleteOrder = 'Are you sure you want to delete \"%s\" quotation ?';
	$sc_ConfirmDeleteProductFromCart = 'Are you sure you want to move \"%s\" product ?';
	
	$sc_AskInput = 'Please enter';
	$sc_no_select = 'No selection';
	
	$sc_clear_cart = 'Clear cart';
	
	$sc_buy = 'Bring in quotation';
	$sc_buy_all = 'Bring checked items in quotation';
	$sc_export = 'Export';
?>
