<?php
require($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = "Bestandstype";
$strModified = "Gewijzigd";
$strSize = "Grootte";
$fbRefresh = "Vernieuwen";
$fbProperties = "Eigenschappen";
$fbNewFolder = "Nieuwe map";
$fbDelete = "Verwijder";
$fbCut = "Knippen";
$fbPaste = "Plakken";
$fbCopy = "Kopiëren";
$fbFiletypes = "Bestandstypes";
$fbPath = "Pad";
$fbFolders = "mappen";
$fbNoSelect = "U heeft niks geselecteerd";
$fbConfirmDelete = "Verwijderen bevestigen";
$fbWritePermissions = "Schrijfrechten";
$fbReadPermissions = "Leesrechten";
$fbGeneral = "Algemeen";
$fbConfirmOverwrite = "Overschrijven bevestigen";
$strOverwritePrefix = "Weet u zeker dat u ";
$strOverwriteSuffix = " wilt overschrijven?";
$fbDescription = "Beschrijving";
$fbLocation = "Lokatie";
$fbUpload = "Uploaden";
$fbUpload_nofile = "Bestand was niet ontvangen.";
$fbDelete_version = "Weet u zeker dat u deze versie wilt verwijderen?";
$fbFolderExists = "De mapnaam bestaat al.";
$fbInherit = "Neem rechten van de moedermap over.";
$fbEmailFile = "e-mail bestand";
$fbFolder = "Map";
$fbSelect = "Selecteer bestand...";
$fbNoFile = "Het bestand dat u probeerde op te slaan is te groot.<br /> De maximaal overdraagbare bestandsgrootte is ingesteld op: ";
$fbPleaseWait = "Even geduld a.u.b. Bezig met verzenden...";
$fbFilename = "Bestandsnaam";
$fbUpLevel = "Omhoog";
$fbItems = "item(s)";
$fbFolderSize = "Grootte van deze map";
$fbMaxUploadSize = "Maximale grootte";
$fbNoRightToOverwrite = "Het bestand bestaat al en u bent niet gemachtigd om deze te overschrijven.";
$fbSaveFile = "Bestand Opslaan Als...";
$fbNameExists = "De opgegeven naam bestaat al in deze map.";
$fbThis = 'deze';
$fbFiles = 'Bestanden';
$fs_no_multi_select = 'U kunt bij deze optie niet meer dan 1 object selecteren.';
$cms_untitled = 'Naamloos';
$cms_insert_file = 'Bestand invoegen';
$cms_preview = 'Weergeven';
$cms_keywords = 'Sleutelwoorden';
$cms_priority = 'Volgorde';
$cms_hide_folder = 'Verberg deze map op de site';
$cms_theme = 'Thema';
$cms_use_go_auth = 'gebruik Group-Office authenticatie op deze site';
$cms_search_files_prefix = 'De HTML bestanden dat het woord';
$cms_search_files_suffix = 'zijn automatisch geselecteerd. Klik op \'Ok\' om de selectie op te slaan';
$cms_new_site = 'Nieuwe site';
$cms_search_files = 'Doorzoeken';
$cms_subscribe = 'Aanmelden';
$cms_sites = 'site(s)';
$cms_style = 'Stijlen';
$cms_insert_file_url = 'URL invoegen';
$cms_templates = 'Sjablonen';
$cms_files = 'Bestanden';
$cms_items = 'item(s)';
$cms_header = 'Kopstuk';
$cms_footer = 'Voetstuk';
$cms_new_theme = 'Nieuw thema';
$cms_themes = 'Thema(\'s)';
$cms_themes_menu = 'Thema\'s';
$cms_all_sites = 'Alle sites';
$cms_your_sites = 'Uw sites';
$cms_cmd_new_site = 'Nieuwe site';
$cms_template_items = 'Sjablonen';
$cms_new_template_item = 'Nieuw sjabloon';

$cms_found_one = '1 bestand gevonden';
$cms_found = 'bestanden gevonden';
$cms_empty = 'Dit gedeelte is leeg en waarschijnlijk in onderhoud.';
$cms_new_page = 'Nieuwe&nbsp;pagina';

$cms_search_words = 'Zoekwoorden';
$cms_no_themes = 'U heeft nog geen thema\'s. Maak eerst een thema.';

$cms_edit_search_words = 'zoekwoorden aanpassen';
$cms_id = 'Site ID';

$cms_cleanup = 'HTML&nbsp;Opschonen';
$cms_settings = 'Instellingen';
$cms_site_exists = 'Er bestaat al een site met deze naam';
$cms_main_template = 'Hoofd';
$cms_confirm_close = 'Wijzigingen gaan verloren. Weet u het zeker?';

$cms_additional_style = 'Stijl die in de tekstverwerker wordt weergegeven';
$cms_restrict_editor = 'Beperk tekstverwerker tot de gedefinieerde stijlen';
$cms_enable_publish = 'Schakel lokale website publicatie in';
$cms_path_not_writable = 'Het pad dat u invoerde is ongeldig of niet beschrijfbaar voor Group-Office.';

$cms_publish = 'Publicatie';
$cms_path_already_used = 'Het pad dat u heeft opgegeven wordt al gebruikt door een andere website.';
$cms_site_offline = 'Deze site is momenteel niet beschikbaar gesteld.';

$cms_disable_publish = 'Schakel publicatie uit';
$cms_publish_dynamic = 'Publiceer website dynamisch';
$cms_publish_static = 'Publiceer website statisch';

$cms_sendmail_error = 'Het bericht kon niet worden verzonden. Probeer het a.u.b. opnieuw.';
$cms_sendmail_success = 'Dank u wel. Het bericht is verzonden.';
$cms_message = 'Bericht';
$cms_subject = 'Onderwerp';
$cms_domain = 'Domein';
$cms_replace_filenames = 'Vervang bestandsnamen';

//2.06
$cms_multipage_display = 'Wordt deze website gepresenteerd in knipselopmaak';
$cms_hot_item = 'Geef deze pagina weer bij de Hot items';
$cms_normal_display = 'Wordt het eerste bestand uit de geopende map weergegeven';
$cms_display_type = 'Wanneer een bezoeker een map opent:';
$cms_read_more = 'Lees meer';

$cms_disable_multipage = 'Geen knipselopmaak';
?>
