<?php
require($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$ft_title = "Filtyper";
$ft_text = "Filtyper bliver automatisk tilføjet af Group-Office. Du kan ændre ikoner og navne her.";

$ft_icon = "Ikon";
$ft_extension = "Type";
$ft_friendly = "Beskrivelse";
$ft_content = "Indhold";
$ft_no_filetypes = "Der blev ikke fundet nogen filtyper.";
$ft_upload_text = "Vælg et ikon at overføre. Kun GIF filer accepteres.";
$ft_no_file = "Ingen filer blev overført.";
$ft_please_wait = "Vent mens ikonet overføres...";
$ft_properties = "Egenskaber";
$ft_filename = "Filnavn";
$ft_current_icon = "Aktuelt ikon";
?>
