<?php
require($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$ft_title = "Clases de Archivo";
$ft_text = "Las clases de archivo est&aacute;n autom&aacute;ticamente adicionadas por Group-Office. Usted puede cambiar los iconos y nombres aqu&iacute;.";

$ft_icon = "Icon";
$ft_extension = "Extensi&oacute;n";
$ft_friendly = "Seud&oacute;nimo";
$ft_content = "Tipo de Contenido";
$ft_no_filetypes = "No se encontraron archivos.";
$ft_upload_text = "Seleccione el icono del archivo a actualizar. Unicamente se aceptan archivos .GIF.";
$ft_no_file = "Ning&uacute;n archivo fue recibido.";
$ft_please_wait = "Por favor espere mientras se actualiza el icono...";
$ft_properties = "Propiedades";
$ft_filename = "Nombre de archivo";
$ft_current_icon = "Icono actual";
?>
