<?php
require($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$ft_title = "Types de fichiers";
$ft_text = "Les types de fichiers sont automatiquement ajoutés par Group-Office. Vous pouvez changer les icônes et les noms içi.";

$ft_icon = "Icône";
$ft_extension = "Extension";
$ft_friendly = "Surnom";
$ft_content = "Type de contenu";
$ft_no_filetypes = "Pas de type de fichiers trouvés.";
$ft_upload_text = "Choisissez l'icône du type de fichier à charger. Seuls les fichiers GIF sont acceptés.";
$ft_no_file = "Aucun fichier reçu.";
$ft_please_wait = "Patientez pendant que l'icône est téléchargé...";
$ft_properties = "Propriétés";
$ft_filename = "Nom de fichier";
$ft_current_icon = "Icône en cours";
?>