<?php
require($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$ft_title = "Tipi di file";
$ft_text = "I tipi di file vengono aggiunti automaticamente da Group-Office. Qui è possibile cambiarne icona e nome.";

$ft_icon = "Icona";
$ft_extension = "Estensione";
$ft_friendly = "Descrizione";
$ft_content = "Tipo contenuto";
$ft_no_filetypes = "Nessun tipo di file trovato.";
$ft_upload_text = "Seleziona l'icona da importare. Sono accettati solo file GIF.";
$ft_no_file = "File non ricevuto.";
$ft_please_wait = "Importazione dell'icona in corso...";
$ft_properties = "Proprietà";
$ft_filename = "Nome file";
$ft_current_icon = "Icona corrente";
?>
