<?php
require($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$ft_title = "Tipos de Arquivos";
$ft_text = "Os Tipos de Arquivos são automaticamente adicionados pelo Group-Office. Você pode alterar os ícones e nomes aqui.";
$ft_icon = "Ícones";
$ft_extension = "Extensão";
$ft_friendly = "Nome amigável";
$ft_content = "Tipo de conteúdo";
$ft_no_filetypes = "Nenhums tipos de arquivos foram encontrados.";
$ft_upload_text = "Selecione o ícone que você quer enviar para representar este tipo de arquivo. Apenas arquivos do tipo GIF são aceitos.";
$ft_no_file = "Nenhum arquivo foi recebido.";
$ft_please_wait = "Por favor aguarde durante a fase de envio deste ícone...";
$ft_properties = "Propriedades";
$ft_filename = "Nome de Arquivo";
$ft_current_icon = "Ícone atual";
?>
