<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$ft_title = "Filtyper";
$ft_text = "Filtyper är automatiskt inlaggda av Group-Office. DU kan ändra ikoner och namn här.";

$ft_icon = "Ikon";
$ft_extension = "Ändelse";
$ft_friendly = "Smeknamn";
$ft_content = "Innehållstyp";
$ft_no_filetypes = "Inga filtyper funna.";
$ft_upload_text = "Välj den filtypsikonen att ladda upp. Endast GIF-filer accepteras";
$ft_no_file = "Ingen fil mottogs.";
$ft_please_wait = "Var god vänta medans uppladdning av ikoner sker...";
$ft_properties = "Egenskaper";
$ft_filename = "Filnamn";
$ft_current_icon = "Nuvarande ikon";
?>
