<?php
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Sprache";
$pref_theme = "Thema";
$pref_date_format = "Datumsformat";
$pref_thousands_seperator = "Tausender-Trennzeichen";
$pref_decimal_seperator = "Dezimalstellen-Trennzeichen";
$pref_mail_client = "Benutze den Email-Client von Group-Office f&uuml;r den Emailversand.";
$pref_look = "Erscheinungsbild";
$pref_notations = "Darstellungsarten";
$pref_currency = 'W&auml;hrung';
$pref_region_code = 'Region';
$pref_max_rows_list = 'Zeilenanzahl je Seite';
$pref_unlimited = 'unbegrenzt';
$pref_timezone = 'Zeitzone';
$pref_time_format = "Zeitformat";
$pref_startmodule = 'Starte mit';

//2.01
$pref_first_weekday = 'Erster Wochentag';

//2.05
$adjust_to_dst = 'Uhrzeit automatisch an Sommerzeit anpassen';
?>
