<?php
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Sprog";
$pref_theme = "Tema";
$pref_date_format = "Datoformat";
$pref_thousands_seperator = "Talseparator";
$pref_decimal_seperator = "Decimaltegn";
$pref_mail_client = "Brug Group-Office mailprogrammet til at sende mail.";
$pref_look = "Udseende";
$pref_notations = "Formater";
$pref_currency = 'Møntfod';

//translation required
$pref_region_code = 'Region'
?>
