<?php
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Idioma";
$pref_theme = "Tema";
$pref_date_format = "Formato de Fecha";
$pref_thousands_seperator = "Separador de Miles";
$pref_decimal_seperator = "Separador Decimal";
$pref_mail_client = "Use el cliente de correo de Group-Office para enviar E-mail.";
$pref_look = "Aspecto";
$pref_notations = "Formato";
$pref_currency = 'Moneda local';
$pref_region_code = 'C&oacute;digo de &aacute;rea';
$pref_max_rows_list = 'Maximum number of rows in lists';
$pref_unlimited = 'Ilimitado';?>
