<?php
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Langue";
$pref_theme = "Thème";
$pref_date_format = "Format de la date";
$pref_thousands_seperator = "Séparateur des milliers";
$pref_decimal_seperator = "Séparateur décimal";
$pref_mail_client = "Utiliser le client mail de Group-Office pour envoyer le courrier.";
$pref_look = "Apparence";
$pref_notations = "Notations";
$pref_currency = 'Monétaire';
$pref_region_code = 'Région';
$pref_max_rows_list = 'Nombre maximum de lignes dans les listes';
$pref_unlimited = 'Illimité';
$pref_timezone = 'Fuseau horaire';
$pref_time_format = "Fuseau horaire";
$pref_startmodule = 'Commencez avec le module'; //Start in module

//2.01
$pref_first_weekday = 'Premier jour de la semaine'; //First weekday

//2.05
$adjust_to_dst = 'Automatically adjust time to Daylight Savings Time';
?>