<?php
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Idioma";
$pref_theme = "Tema";
$pref_date_format = "Formato da data";
$pref_thousands_seperator = "Separador dos milhares";
$pref_decimal_seperator = "Separador dos decimais";
$pref_mail_client = "Usar o módulo de correio eletrônico do Group-Office para enviar E-mail.";
$pref_look = "Estilo";
$pref_notations = "Anotações";
$pref_currency = 'Moeda';
$pref_region_code = 'Região';
$pref_max_rows_list = 'Número máximo de colunas em uma lista';
$pref_unlimited = 'Ilimitado';
$pref_timezone = 'Fuso horário';
$pref_time_format = "Formato da hora";
$pref_startmodule = 'Iniciar no módulo';

// 2.01
$pref_first_weekday = 'Primeiro dia da semama';

//2.05
$adjust_to_dst = 'Ajustar automaticamente para Daylight Savings Time';
?>
