<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Ngôn ngữ";
$pref_theme = "Kiểu dáng";
$pref_date_format = "Định dạng ngày";
$pref_thousands_seperator = "Dấu phân cách hàng ngàn";
$pref_decimal_seperator = "Dấu thập phân";
$pref_mail_client = "Dùng HPT-OBM mail để gửi E-mail.";
$pref_look = "Cảm nhận";
$pref_notations = "Ký hiệu";
$pref_currency = 'Tiền tệ';
$pref_region_code = 'Vùng';
$pref_max_rows_list = 'Số dòng tối đa trong danh sách';
$pref_unlimited = 'Không giới hạn';
$pref_timezone = 'Múi giờ';
$pref_time_format = "Định dạng giờ";
$pref_startmodule = 'Bắt đầu với';

//2.01
$pref_first_weekday = 'Ngày đầu tiên trong tuần';

//2.05
$adjust_to_dst = 'Tự động thay đổi giờ theo Daylight Savings Time';
?>
