<?php
require($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Enregistrer le favoris";
$bm_new_window = "Ouvrir le favoris dans une nouvelle fenêtre.";
$bm_current_page = "Page en cours";
$bm_no_bookmarks = "Vous n'avez pas de favoris.";

//2.03
$bm_catagory_exists = 'Une catégorie avec le même nom existe déjà';
$bm_private = 'Privé';
$bm_catagory_other = 'Autre';
$bm_add_bookmark = 'Nouveau Favoris';
$bm_add_catagory = 'Nouvelle Catégorie';
$bm_no_bookmarks_in_catagory = 'Aucuns favoris trouvés dans cette catégorie';
$bm_catagory = 'Catégorie';
$bm_no_select = 'Aucun favoris sélectionnés';

$bm_bookmarks = 'favoris';
$bm_and_all_contents = 'et tous le contenu';

$bm_copy_read_permissions = 'Copier les permissions de lecture vers les favoris';
$bm_copy_write_permissions = 'Copier les permissions d\'écriture vers les favoris';

$bm_move_to_catagory = 'Déplacer les favoris sélectionnés vers la catégorie...';
?>