<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Lưu đánh dấu trang";
$bm_new_window = "Mở đánh dấu trang trong cửa sổ mới.";
$bm_current_page = "Trang hiện tại";
$bm_no_bookmarks = "Bạn chưa có trang nào được đánh dấu.";

//2.03
$bm_catagory_exists = 'Đã tồn tại thể loại này';
$bm_private = 'Private';
$bm_catagory_other = 'Other';
$bm_add_bookmark = 'Thêm đánh dấu trang';
$bm_add_catagory = 'Thêm loại';
$bm_no_bookmarks_in_catagory = 'Không có đánh dấu trang thuộc loại này';
$bm_catagory = 'Thể loại';
$bm_no_select = 'Bạn chưa chọn đánh dấu trang nào';

$bm_bookmarks = 'các đánh dấu trang';
$bm_and_all_contents = 'và tất cả nội dung';

$bm_copy_read_permissions = 'Copy read permissions to bookmarks';
$bm_copy_write_permissions = 'Copy write permissions to bookmarks';

$bm_move_to_catagory = 'Chuyển các đánh dấu trang được chọn tới thể loại...';
?>
