<?php
require($GO_LANGUAGE->get_fallback_language_file('email'));

//Email
$ml_from = "Fra";
$ml_to = "Til";
$ml_send = "Send";
$ml_attach = "Vedhæft";
$ml_attachments = "Vedhæftede filer";
$ml_attachment = "Vedhæftet fil";
$ml_high = "Høj";
$ml_normal = "Normal";
$ml_low = "Lav";
$ml_priority = "Prioritet";
$ml_subject = "Emne";
$ml_filename = "Filnavn";
$ml_total_size = "Total størrelse";
$ml_size = "Størrelse";
$ml_to_empty = "Du skal indtaste en modtager.";
$ml_print = "Udskriv";
$fbNoSelect = "Du skal vælge en besked";

$ml_inbox = 'indbakke';
$ml_properties = 'egenskaber';
$ml_add_account = "Tilføj en konto";
$em_new_folder = "Ny mappe";
$ml_your_accounts = "Dine mail konti";
$ml_no_accounts = "Du har ikke konfigureret nogen mailkonti.";
$ml_original_follows = "----- Original besked -----";
$ml_welcome = "Velkommen til Group-Office mail";
$ml_text = "Klik på konti for at tilføje en mailkonto.";
$ml_accounts = "Konti";
$ml_compose = "Skriv ny";
$ml_delete = "Slet";
$ml_refresh = "Opdater";
$ml_reply = "Besvar";
$ml_forward = "Videresend";
$ml_reply_all = "Besvar alle";
$ml_delete_message = "Er du sikker på du vil slette beskeden permanent?";
$ml_no_subject = "Intet emne";
$ml_no_reciepent = "Ukendt modtager";
$ml_online_files = "Online filer";
$ml_send_error = "Kunne ikke sende besked.";

$ml_attach_forget = "Du har valgt en fil, men den er ikke vedhæftet.";
$ml_messages = "besked(er)";
$ml_message = 'denne besked';
$ml_messages2 = 'beskeder';
$ml_new = "nye";
$ml_delete_mailbox = "Er du sikker på du vil slette de markerede beskeder permanent?";

$contact_profile = "Kontakt profil";
$ml_add_contact = "Tilføj afsender til kontakter";
$strHost = "Server";
$strDefault = "Standard";
$ml_edit_account = "Ret konto";
$ml_new_account = "Ny konto";
$ml_no_messages = "Der er ingen beskeder i denne mappe.";
$ml_file_too_big = "Filen du forsøgte at tilføje er for stor, størrelsen for vedhæftede filer er sat til: ";
$fbNoRightToOverwrite = "Filen eksisterer allerede, og du har ikke rettigheder til at overskrive den.";
$ml_save_attachment = "Gem vedhæftet fil i Group-Office.";
$ml_folders = "Mapper";

$ml_select_folder = "Vælg den folder hvor Group-Office skal gemme sendt post eller indtast et navn for at oprette en folder";
$ml_connect_failed = "Kunne ikke kontakte mailserveren:";
$ml_at_port = "at port";
$ml_solve_error = 'Klik på  \'Konti\' for at ændre din konto indstillinger eller klik på \'Opdater\' for at åbne din standard konto.';
$ml_sent_items = "Sendt post";
$ml_spam = "Spam";
$ml_use = "Brug";
$ml_synchronise = "Synkroniser";
$ml_move_mail = "Flyt valgte beskeder til mappen...";
$ml_filters = "Filtre";
$ml_move_to = "og flyt beskeden til mappen:";
$ml_email_is = "Hvis afsenders mailadresse indeholder:";
$ml_to_is = "Hvis modtagerfeltet indeholder:";
$ml_cc_is = "Hvis Cc feltet indeholder:";

$ml_subject_is = "Hvis emnet indeholder:";
$ml_new_filter = "Nyt filter:";
$ml_field = "Felt";
$ml_contains = "Indeholder";
$ml_folder = "Mappe";
$ml_no_folders = "Du har ingen mapper, så du kan ikke oprette filtre.";
$ml_unwanted = "Klik her hvis beskeden fra afsenderen er uønsket";
$fbFolderSize = "Størrelse på mappen";
$ml_move_up = "Høj prioritet";
$ml_delete_filter = "Er du sikker på du vil slette dette filter?";
$ml_high_priority = "Denne besked har høj prioritet!";
$ml_low_priority = "Denne besked har lav prioritet.";
$ml_block = "Bloker afsender";
$ml_sent_items_fail = "Beskeden blev sendt, men der opstod en fejl da beskeden skulle oprettes i Sendt Post mappen. Kontroller din IMAP konto.";
$fbProperties = "Egenskaber";
$ml_notification = "Anmod om bekræftelse når beskeden er læst";
$ml_ask_notify = "Afsender har anmodet om bekræftelse for læst post. Ønsker du at sende en bekræftelse?";
$ml_displayed = "Den følgende besked er blevet vist til ";
$ml_notify = "Besked ved læsning";
$ml_delete_filter1 = "Slet filter";
$ml_html_message_attached = "Original HTML besked er vedhæftet";
$ml_add_recievers = "Tilføj ukendte modtagere til adressebogen";
$ml_no_folders = 'Du har ingen mapper at filtrere';
$ml_no_filters = 'Du har ingen filtre.';

$ml_host = 'Server';
$ml_port = 'Port';
$ml_type = 'Type';

$ml_loose_changes = 'Ændringer vil gå tabt. Er du sikker?';
$ml_format = 'Format';

$ml_servertype = 'Servertype';
$ml_markread = "Marker som læst";
$ml_markunread = "Marker som ulæst";
$ml_root_mailbox = "rod postkassen";
$ml_inside = "i";

//translation required
$ml_no_mailbox = "Not a mailbox. This folder is not capable to hold any messages.";
?>
