<?php
require($GO_LANGUAGE->get_fallback_language_file('email'));

//Email
$ml_from = "Von";
$ml_to = "An";
$ml_send = "Senden";
$ml_attach = "Anh&auml;ngen";
$ml_attachments = "Anh&auml;nge";
$ml_attachment = "Anhang";
$ml_high = "Hoch";
$ml_normal = "Normal";
$ml_low = "Niedrig";
$ml_priority = "Priorit&auml;t";
$ml_subject = "Betreff";
$ml_filename = "Dateiname";
$ml_total_size = "Gesamtgroesse";
$ml_size = "Groesse";
$ml_to_empty = "Sie haben keinen Empfänger angegeben.";
$ml_print = "Drucken";
$fbNoSelect = "Sie haben keine Nachricht ausgewählt";

$ml_inbox = 'Posteingang';
$ml_properties = 'Eigenschaften';
$ml_add_account = "Ein Postfach einrichten";
$em_new_folder = "Neuer Ordner";
$ml_your_accounts = "Ihre Email-Postf&auml;cher";
$ml_no_accounts = "Sie haben noch keine Email-Postf&auml;cher eingerichtet.";
$ml_original_follows = "----- Originalnachricht -----";
$ml_welcome = "Willkommen zu Group-Office Email";
$ml_text = "Klicken Sie auf Konten, um ein Email-Postfach einzurichten.";
$ml_accounts = "Konten";
$ml_compose = "Neue Nachricht";
$ml_delete = "L&ouml;schen";
$ml_refresh = "Aktualisieren";
$ml_reply = "Antworten";
$ml_forward = "Weiterleiten";
$ml_reply_all = "Allen Antworten";
$ml_delete_message = "Sind Sie sicher, dass Sie diese Nachricht endgültig löschen möchten?";
$ml_no_subject = "Kein Betreff";
$ml_no_reciepent = "Ungenannter Empf&auml;nger";
$ml_online_files = "Online-Dateien";
$ml_send_error = "Der Email-Versand ist fehlgeschlagen.";

$ml_attach_forget = "Sie haben zwar eine Datei ausgewählt, aber noch nicht angehangen.";
$ml_messages = "Nachricht(en)";
$ml_message = 'diese Nachricht';
$ml_messages2 = 'Nachrichten';
$ml_new = "Neu";
$ml_delete_mailbox = "Sind Sie sicher, dass Sie die ausgewählten Nachrichten endgültig löschen möchten?";

$contact_profile = "Kontaktprofil";
$ml_add_contact = "Absender zur Kontaktliste hinzuf&uuml;gen";
$strHost = "Host";
$strDefault = "Standard";
$ml_edit_account = "Postfach bearbeiten";
$ml_new_account = "Neues Postfach";
$ml_no_messages = "Keine Nachrichten in diesem Ordner.";
$ml_file_too_big = "Die anzuhängende Datei ist zu gross. Die maximale Grösse fuer einen Dateianhang ist: ";
$fbNoRightToOverwrite = "Die Datei existiert bereits, und Sie haben nicht die Berechtigung diese zu ueberschreiben.";
$ml_save_attachment = "Dateianhang in Group-Office speichern.";
$ml_folders = "Ordner";

$ml_select_folder = "Bitte den Ordner fuer die gesendeteten Nachrichten angeben. Oder geben Sie unten einen Ordnernamen ein, um diesen neu anzulegen.";
$ml_connect_failed = "Verbindungsversuch zum Mailserver fehlgeschlagen:";
$ml_at_port = "Am Port";
$ml_solve_error = 'Klicken Sie auf \'Postf&auml;cher\', um Ihre Postfacheinstellungen zu korrigieren, oder klicken Sie auf \'Aktualisieren\', um Ihr Standard-Postfach zu oeffnen.';
$ml_sent_items = "Gesendet";
$ml_spam = "Spam";
$ml_use = "In Verwendung";
$ml_synchronise = "Synchronisieren";
$ml_move_mail = "Verschiebe selektierte Nachrichten in den Ordner...";
$ml_filters = "Filter";
$ml_move_to = "dann verschiebe die Nachricht in den Ordner:";
$ml_email_is = "Wenn das Absender-Feld enth&auml;lt:";
$ml_to_is = "Wenn das Empf&auml;nger-Feld enth&auml;lt:";
$ml_cc_is = "Wenn das CC-Feld enth&auml;lt:";

$ml_subject_is = "Wenn die Betreffzeile enth&auml;lt:";
$ml_new_filter = "Neuer Filter:";
$ml_field = "Feld";
$ml_contains = "Enth&auml;lt";
$ml_folder = "Ordner";
$ml_no_folders = "Sie haben noch keine Ordner, daher ist es nicht moeglich, Filter zu definieren.";
$ml_unwanted = "Bitte hier klicken, wenn Nachrichten von diesem Absender unerwuenscht sind";
$fbFolderSize = "Groesse des Ordners";
$ml_move_up = "Priorit&auml;t anheben";
$ml_delete_filter = "Sind Sie sicher, dass Sie diesen Filter entfernen möchten?";
$ml_high_priority = "Diese Nachricht hat eine hohe Priorit&auml;t!";
$ml_low_priority = "Diese Nachricht hat eine niedrige Priorit&auml;t.";
$ml_block = "Absender blocken";
$ml_sent_items_fail = "Diese Nachricht ist versendet worden. Allerdings hat es einen Fehler gegeben beim Speichern dieser Nachricht im Ordner fuer gesendete Nachrichten. Bitte ueberpruefen Sie Ihr IMAP-Postfach.";
$fbProperties = "Eigenschaften";
$ml_notification = "Vom Empf&auml;nger eine Lesebenachrichtigung anfordern";
$ml_ask_notify = "Der Absender dieser Nachricht hat eine Lesebenachrichtigung angefordert. Sind Sie damit einverstanden, dass der Absender diese bekommt?";
$ml_displayed = "Die nachfolgende Nachricht wurde gesichtet von ";
$ml_notify = "Lesebenachrichtigung";
$ml_delete_filter1 = "Loeschfilter";
$ml_html_message_attached = "Die originalen HTML-Nachrichten sind angehaengt";
$ml_add_recievers = "Unbekannte Empf&auml;nger in das Adressbuch uebernehmen";
$ml_no_filters = 'Sie haben noch keine Filter.';

$ml_host = 'Mailserver';
$ml_port = 'Port';
$ml_type = 'Typ';
$ml_servertype = 'Servertyp';
$ml_loose_changes = 'Alle Änderungen werden verloren gehen. Sind Sie sicher?';
$ml_format = 'Format';

$ml_markread = "gelesen";
$ml_markunread = "ungelesen";
$ml_root_mailbox = "Stammordner";
$ml_inside = "Im";

$ml_no_mailbox = "Keine Mailbox. Dieser Ordner kann keine Nachrichten enthalten.";
$ml_signature = 'Signatur';
$ml_root = 'Stammordner';
$ml_disable_accounts = 'Kontenverwaltung deaktivieren';
$ml_trash = 'Papierkorb';
$ml_disable = 'Deaktivieren';

$ml_confirm_empty_mailbox = 'Der aktuelle Ordner wird geleert! Sind Sie sicher?';
$ml_empty_mailbox = 'Ordner&nbsp;leeren';

$ml_you_have = 'Sie haben';
$ml_new_mail_single = 'neue Email-Nachricht.';
$ml_new_mail_multiple = 'neue Email-Nachrichten.';

$ml_auto_check = 'Automatische Benachrichtigung bei neuen Emails.';

$ml_no_contacts_in_mailing_group = 'Die selektierte Mailing-Gruppe enth&auml;lt keine Kontakte. Bitte zuerst Kontakte hinzuf&uuml;gen.';
$ml_attention= 'Achtung';

//2.02
$ml_autocheck_disabled = ' konnte nicht erreicht werden. Die automatische Ueberpruefung nach neuen Mails ist auf diesem Konto ausgeschaltet.';
$ml_mark = 'Nachrichten markieren als...';
$ml_flag = 'gekennzeichnet';
$ml_clearflag = 'nicht gekennzeichnet';
$ml_expand_all = 'Alle Ordner ausklappen';
$ml_collapse_all = 'Alle Ordner zusammenklappen';

//2.05
$ml_search = 'Suchen';
$ml_answered = 'beantwortet';
$ml_doesnt_matter = 'nicht relevant';
$ml_body = 'Nachricht';
$ml_before = '&auml;lter als';
$ml_since = 'neuer als';
$ml_select_one_criteria = 'Bitte wenigstens einen Suchbegriff eingeben.';
?>
