<?php
require($GO_LANGUAGE->get_fallback_language_file('email'));

//Email
$ml_from = "De";
$ml_to = "Para";
$ml_send = "Enviar";
$ml_attach = "Adjuntar";
$ml_attachments = "Archivos Adjuntos";
$ml_attachment = "Adjuntar";
$ml_high = "Alto";
$ml_normal = "Normal";
$ml_low = "Baja";
$ml_priority = "Prioridad";
$ml_subject = "Asunto";
$ml_filename = "Nombre de Archivo";
$ml_total_size = "Tama&ntilde;o total";
$ml_size = "Tama&ntilde;o";
$ml_to_empty = "No especific&oacute; un receptor.";
$ml_print = "Imprimir";
$fbNoSelect = "No seleccion&oacute; un mensaje";

$ml_inbox = 'recibidos';
$ml_properties = 'propiedades';
$ml_add_account = "Agregar una cuenta";
$em_new_folder = "Nueva carpeta";
$ml_your_accounts = "Sus cuentas de correo";
$ml_no_accounts = "No tiene cuentas de correo configuradas.";
$ml_original_follows = "----- Mensaje Original -----";
$ml_welcome = "Bienvenido al m&oacute;dulo de Correo Electr&oacute;nico";
$ml_text = "Haga click en cuentas para agregar una cuenta de correo.";
$ml_accounts = "cuentas";
$ml_compose = "redactar";
$ml_delete = "borrar";
$ml_refresh = "refrescar";
$ml_reply = "replicar";
$ml_forward = "reenviar";
$ml_reply_all = "reenviar a todos";
$ml_delete_message = "Está seguro que desea borrar este mensaje permanentemente?";
$ml_no_subject = "Sin asunto";
$ml_no_reciepent = "Receptor no conocido";
$ml_online_files = "Archivos en linea";
$ml_send_error = "Falla en el envio del correo.";

$ml_attach_forget = "Selecciona un archivo pero no lo adjunta.";
$ml_messages = "mensaje(s)";
$ml_message = 'este mensaje';
$ml_messages2 = 'mensajes';
$ml_new = "nuevo";
$ml_delete_mailbox = "Está seguro de eliminar los correos seleccionados permanentemente?";

$contact_profile = "Perfil de contactos";
$ml_add_contact = "Adicionar remitente a contactos";
$strHost = "Nombre M&aacute;quina";
$strDefault = "Est&aacute;ndar";
$ml_edit_account = "Editar cuenta";
$ml_new_account = "Nueva cuenta";
$ml_no_messages = "No hay mensajes en esta carpeta.";
$ml_file_too_big = "El archivo que trata de adjuntar es demasiado grande, el m&aacute;ximo tama&ntilde;o para archivos adjuntos es: ";
$fbNoRightToOverwrite = "El archivo existe y no tiene permiso para sobreescribirlo.";
$ml_save_attachment = "Grabar adjuntos en el Group-Office.";
$ml_folders = "carpetas";

$ml_select_folder = "Seleccione la carperpeta donde se puedan almacenar los correos enviados o ingrese un nombre para crear una carpeta";
$ml_connect_failed = "Falla en la conexi&oacute;n al servidor de correo:";
$ml_at_port = "en el puerto";
$ml_solve_error = 'Haga click en \'Cuenta\' para modificar la configuraci&oacute;n de la cuenta o haga click en \'Refrescar\' para abrir su cuenta por defecto.';
$ml_sent_items = "Items enviados";
$ml_spam = "Spam";
$ml_use = "Usar";
$ml_synchronise = "sincronizar";
$ml_move_mail = "Mover mensajes seleccionados a...";
$ml_filters = "filtros";
$ml_move_to = "luego mueva los mensajes a la carpeta:";
$ml_email_is = "Si la direcci&oacute;n del remitente contiene:";
$ml_to_is = "Si el campo del destinatario contiene:";
$ml_cc_is = "Si el campo de copia a contiene:";

$ml_subject_is = "Si el asunto contiene:";
$ml_new_filter = "Nuevo filtro:";
$ml_field = "Campo";
$ml_contains = "Contiene";
$ml_folder = "Carpeta";
$ml_no_folders = "No tiene carpetas donde crear filtros.";
$ml_unwanted = "Haga click aqu&iacute; si el remitente es no deseado";
$fbFolderSize = "Tama&ntilde;o de la carpeta";
$ml_move_up = "Incrementar prioridad";
$ml_delete_filter = "Está seguro de querer borrar este filtro?";
$ml_high_priority = "Este mensaje tiene alta prioridad!";
$ml_low_priority = "Este mensaje tiene baja prioridad.";
$ml_block = "bloquear remitente";
$ml_sent_items_fail = "El mesaje fue enviado pero ocurri&oacute; un error mientras se creaba este mensaje en la carpeta de enviados. Verifique su cuenta IMAP.";
$fbProperties = "propiedades";
$ml_notification = "El receptor requiere el envio de un mensaje de notificaci&oacute;n de lectura";
$ml_ask_notify = "El remitente de este mensaje ha solicitado un mensaje de notificaci&oacute;n de lectura de usted. Desea responder?";
$ml_displayed = "El siguiente correo ha sido mostrado a  ";
$ml_notify = "Notificaci&oacute;n de Lectura";
$ml_delete_filter1 = "Borrar filtro";
$ml_html_message_attached = "Los mensajes en HTML son adjuntados";
$ml_add_recievers = "Agregar receptor desconocido a su libreta de direcciones";
$ml_no_folders = 'No tiene carpetas para filtrar';
$ml_no_filters = 'No tiene ningun filtro.';

$ml_host = 'M&aacute;quina';
$ml_port = 'Puerto';
$ml_type = 'Tipo';
$ml_servertype = 'Tipo de servidor';
$ml_format = 'Formato';
$ml_loose_changes = 'Se perder&aacute;n los cambios. Est&aacute; seguro?';

$ml_markread = "marcar como le&iacute;do ";
$ml_markunread = "marcar como no le&iacute;do";
$ml_root_mailbox = "raiz de entrados";
$ml_inside = "entrar";

$ml_no_mailbox = "Este no es un mailbox. Este folder no contiene mensajes.";
$ml_signature = 'Firma';
$ml_root = 'Raiz mailbox';

$ml_disable_accounts = 'Disablhabilitar administracion de cuentas';
$ml_trash = 'Basura';
?>
