<?php
require($GO_LANGUAGE->get_fallback_language_file('email'));

//Email
$ml_from = "De";
$ml_to = " Para";
$ml_send = "Enviar";
$ml_attach = "Anexar";
$ml_attachments = "Anexos";
$ml_attachment = "Anexo";
$ml_high = "Elevada";
$ml_normal = "Normal";
$ml_low = "Baixa";
$ml_priority = "Prioridade";
$ml_subject = "Assunto";
$ml_filename = "Nome do arquivo";
$ml_total_size = "Tamanho total";
$ml_size = "Tamanho";
$ml_to_empty = "Você nã especificou um destinatário.";
$ml_print = "Imprimir";
$fbNoSelect = "Você não selecionou uma mensagem.";

$ml_inbox = 'Caixa de Entrada';
$ml_properties = 'Propriedades';
$ml_add_account = "Adicionar uma conta";
$em_new_folder = "Nova Pasta";
$ml_your_accounts = "Suas contas de E-mail";
$ml_no_accounts = "Você não tem nenhuma conta de E-mail configurada.";
$ml_original_follows = "----- Mensagem Original -----";
$ml_welcome = "Bem-vindo ao Group-Office - E-mail";
$ml_text = "Clique sobre Contas para adicionar um cliente de E-mail.";
$ml_accounts = "Contas";
$ml_compose = "Redigir";
$ml_delete = "Excluir";
$ml_refresh = "Atualizar";
$ml_reply = "Responder";
$ml_forward = "Encaminhar";
$ml_reply_all = "Responder a todos";
$ml_delete_message = "Tem certeza que deseja exluir permanentemente esta mensagem?";
$ml_no_subject = "Nenhum assunto";
$ml_no_reciepent = "Destinatário Inválido";
$ml_online_files = "Arquivo online";
$ml_send_error = "Falha ao enviar a mensagem.";

$ml_attach_forget = "Você selecionou um arquivo mas não o anexou.";
$ml_messages = "Mensagem(ns)";
$ml_message = 'Esta mensagem';
$ml_messages2 = 'Mensagens';
$ml_new = "Nova";
$ml_delete_mailbox = "Tem certeza que deseja excluir permanentemente as mensagens selecionadas?";

$contact_profile = "Perfil do contato";
$ml_add_contact = "Adicione o remetente aos contatos";
$strHost = "Servidor";
$strDefault = "Valor comum";
$ml_edit_account = "Edite a sua conta";
$ml_new_account = "Conta nova";
$ml_no_messages = "Não há nenhuma mensagem nesta pasta.";
$ml_file_too_big = "O arquivo que você tentou anexar é muito grande, o tamanho máximo para anexos ésta ajustado para: ";
$fbNoRightToOverwrite = "O arquivo já existe e você nâo tem permissão para sobreescrever o arquivo.";
$ml_save_attachment = "Salvar o arquivo como anexo no Group-Office.";
$ml_folders = "Pastas";

$ml_select_folder = "Selecione a pasta onde o Group-Office pode guardar o correio enviado ou insira um nome abaixo para criar uma pasta";
$ml_connect_failed = "A conecção com o servidor de correio falhou:";
$ml_at_port = "na porta";
$ml_solve_error = 'Clique \'Contas\' para ajustar a sua conta ou clique \'Atualizar\' para abrir uma conta comum.';
$ml_sent_items = "Itens enviados";
$ml_spam = "Spam";
$ml_use = "Uso";
$ml_synchronise = "sincronize";
$ml_move_mail = "Mudar as mensagens selecionadas para a pasta...";
$ml_filters = "Filtros";
$ml_move_to = "Mova a mensagem para a pasta:";
$ml_email_is = "Se o endereço do remetente contém:";
$ml_to_is = "Se o campo de remetentes contém:";
$ml_cc_is = "Se o campo de remetentes em cópia carbono contém:";

$ml_subject_is = "Se o assunto contém:";
$ml_new_filter = "Filtro novo:";
$ml_field = "Campo";
$ml_contains = "Contém";
$ml_folder = "Pasta";
$ml_no_folders = "Você não têm nenhuma pasta então não pode criar filtros.";
$ml_unwanted = "Clique aqui se o E-mail deste remetente não for desejado";
$fbFolderSize = "Tamanho da pasta";
$ml_move_up = "Aumentar a prioridade";
$ml_delete_filter = "Tem certeza que quer excluir este filtro?";
$ml_high_priority = "Esta mensagem tem prioridade elevada!";
$ml_low_priority = "Esta mensagem tem prioridade baixa.";
$ml_block = "Bloquear o remetente";
$ml_sent_items_fail = "A mensagem foi enviada mas houve um erro ao criar esta mensagem na pasta de itens enviados.  Por favor verifique a sua conta IMAP.";
$fbProperties = "Propriedades";
$ml_notification = "Requisite confirmação de leitura";
$ml_ask_notify = "O remetente desta mensagem pediu uma notificação que você leu a mensagem. Deseja emitir um relatório desta mensagem como lida?";
$ml_displayed = "O seguinte E-mail foi indicado a ";
$ml_notify = "Notificação Como Lido";
$ml_delete_filter1 = "Excluir Filtro";
$ml_html_message_attached = "Mensagens originais do tipo HTML estão anexadas";
$ml_add_recievers = "Adicione destinatários desconhecidos ao seu Livro de Endereços";
$ml_no_folders = 'Você não tem nenhuma pasta para onde filtar';
$ml_no_filters = 'Você não tem nenhum filtros.';

$ml_host = 'Servidor';
$ml_port = 'Porta';
$ml_type = 'Tipo';
$ml_servertype = 'Tipo de servidor';
$ml_format = 'Formato';
$ml_loose_changes = 'As mudanças serão perdidas. Tem certeza  que deseja continuar?';

$ml_markread = "marcar como lido";
$ml_markunread = "marcar como não lido";
$ml_root_mailbox = "caixa postal primária";
$ml_inside = "em";

$ml_no_mailbox = "Esta não é uma caixa postal. Esta pasta não contém nenhuma mensagem.";
$ml_signature = 'Assinatura';
$ml_root = 'Caixa postal Primária';
$ml_disable_accounts = 'Administração da Conta disabilitada';
$ml_trash = 'Lixo';

$ml_disable = 'Desativar';
$ml_confirm_empty_mailbox = 'Você tem certeza que deseja esvaziar esta pasta (apagar tudo)?';
$ml_empty_mailbox = 'Esvaziar';
$ml_you_have = 'Você tem';
$ml_new_mail_single = 'nova mensagem.';
$ml_new_mail_multiple = 'nova mensagens.';
$ml_auto_check = 'Verificar automaticamente novas mensagens para esta conta.';
//1.98
$ml_no_contacts_in_mailing_group = 'Não existem contatos na lista de e-mails que você selecionou. Por favor adicione contatos ao grupo primeiro.';
$ml_attention= 'Atenção';

//2.02
$ml_autocheck_disabled = ' não pôde ser encontrado. A verificação automática de mensagens foi desativada para esta conta.';
$ml_mark = 'Marcar mensagens...';
$ml_flag = 'Marcado';
$ml_clearflag = 'Desmarcado';
$ml_expand_all = 'Expandir todas as pastas';
$ml_collapse_all = 'Agrupar todas as pastas';

//2.05
$ml_search = 'Busca';
$ml_answered = 'Resposta';
$ml_doesnt_matter = 'Tanto faz';
$ml_body = 'Corpo';
$ml_before = 'Mais antigo que';
$ml_since = 'Mais novo que';
$ml_select_one_criteria = 'Por favor selecione ou digite pelo menos um critério para busca.';
?>
