<?php
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Du har indtastet en forkert tidsperiode';
$pm_add_hours_success = 'De indtastede data er gemt';
$pm_already_booked = 'Du har allerede en aftale i den periode';
$pm_new_entry = 'Ny aftale ved';
$pm_fees = 'Beløb';
$pm_new_fee = 'Nyt beløb';
$pm_users = 'Brugere';
$pm_materials = 'Materialer';
$pm_new_material = 'Nyt materiale';
$pm_project_data = 'Projekt data fra';
$pm_load= 'Hent';
$pm_enter_data = 'Indtast data';
$pm_value = 'Værdi';
$pm_too_old = 'Du kan ikke indtaste data der er mere end en uge gamle';

$pm_employee = 'Ansatte';
$pm_project = 'Projekt';
$pm_starttime = 'Start tidspunkt';
$pm_endtime = 'Slut tidspunk';
$pm_breaktime = 'Break time';
$pm_this_week = 'Indtastet denne uge';
$pm_no_projects = 'Du har ingen projekter';
$pm_hours = 'Timer';
$pm_total_hours = 'Total antal timer';
$pm_client = 'Klient';
$pm_created_at = 'Oprettet';

$pm_show_all = 'Vis alle';
$pm_show_period = 'Vis alle';
$pm_to = 'til';
$pm_show_month = 'Vis måned';

$pm_total_hours_days = 'Ialt timer/dage';
$pm_projects_count = 'projekt(er)';
$pm_show_data = 'Vis data';
$pm_new_project = 'Nyt projekt';
$pm_other_contacts = 'Andre kontakter';
$pm_no_contacts = 'Du har ingen kontakter der kan bruges som klient til dette projekt. Du skal først oprette kontakter';

//translation required
$pm_unit_value = 'Unit value';
$pm_units = 'Units';
$pm_mins = 'mins';
$pm_no_fees = 'There are no fees created yet. Only a user with administrator privileges can create fees.';
$pm_fee = 'Fee';
$pm_no_contact = 'None';
$pm_load_period= 'Period';
$pm_load_type= 'Load data for';
$pm_total_fee = 'Total fee';
$pm_total_days = 'Total days';
$pm_total_units = 'Total units';
$pm_summary = 'Summary';
?>
