<?php
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Sie haben einen ungueltigen Zeitraum eingegeben';
$pm_add_hours_success = 'Die unten eingegebenen Daten wurden erfolgreich gespeichert';
$pm_already_booked = 'Sie haben bereits in diesem Zeitraum gebucht';
$pm_new_entry = 'Neuer Eintrag am';
$pm_fees = 'Kosten';
$pm_new_fee = 'Neue Kosten';
$pm_users = 'Benutzer';
$pm_materials = 'Material';
$pm_new_material = 'Neues Material';
$pm_project_data = 'Projektdaten vom';
$pm_load= 'Auswerten';
$pm_enter_data = 'Daten eingeben';
$pm_value = 'Wert';
$pm_too_old = 'Es ist nicht moeglich Daten einzugeben, die aelter sind als eine Woche';

$pm_employee = 'Mitarbeiter';
$pm_project = 'Projekt';
$pm_starttime = 'Startzeit';
$pm_endtime = 'Endzeit';
$pm_breaktime = 'Pausenzeit';
$pm_this_week = 'In der aktuellen Woche eingegeben';
$pm_no_projects = 'Sie verfuegen ueber keine Projekte';
$pm_hours = 'Stunden';
$pm_total_hours = 'Gesamte Stundenzahl';
$pm_client = 'Mandant';
$pm_created_at = 'Angelegt am';

$pm_show_all = 'Alle anzeigen';
$pm_show_period = 'Anzeigen von';
$pm_to = 'bis';
$pm_show_month = 'Monat anzeigen';

$pm_total_hours_days = 'Gesamtanzahl von Stunden/Tagen';
$pm_projects_count = 'Projekt(e)';
$pm_show_data = 'Daten anzeigen';
$pm_new_project = 'Neues Projekt';
$pm_other_contacts = 'Sonstige Kontakte';
$pm_no_contacts = 'Sie verfuegen ueber keinen Kontakt, welcher als Mandant fuer dieses Projekt herangezogen werden koennte. Bitte vorher einen entsprechenden Kontakt anlegen';

$pm_unit_value = 'Preis je Einheit';
$pm_units = 'Einheiten';
$pm_mins = 'Minuten';
$pm_no_fees = 'Es sind noch keine Preise gepflegt. Nur ein Anwender mit administrativen Rechten kann Preise einpflegen.';
$pm_fee = 'Kosten';
$pm_no_contact = 'Kein';
$pm_load_period= 'Periode';
$pm_load_type= 'Suche Daten fuer';
$pm_total_fee = 'Summe Preis';
$pm_total_days = 'Summe Tage';
$pm_total_units = 'Summe Einheiten';
$pm_summary = 'Zusammenfassung';
$pm_this_entry = 'Diese Buchung';
$pm_entry = 'Buchung';
$pm_timer_started_at = 'Timer gestartet am';
$pm_start_timer = 'Timer starten';
$pm_stop_timer = 'Timer anhalten';

//translation required
$pm_start_date = 'Startdatum';
$pm_end_date = 'Endedatum';
$pm_responsible = 'Verantwortlicher';
$pm_status = 'Status';

$pm_status_values[1] = 'Beantragt';
$pm_status_values[2] = 'Aktiv';
$pm_status_values[3] = 'Pause';
$pm_status_values[4] = 'Erledigt';
$pm_status_values[5] = 'Fakturiert';

$pm_filter = 'Filter';
$pm_project_exists = 'Ein Projekt mit diesem Namen ist bereits vorhanden';

$pm_clocked_in = 'Zeitnehmer ist aktiv. Zum Stoppen bitte hier klicken';

$pm_alert = 'Dieses Projekt ist ueberfaellig';
$pm_budget = 'Budget';
$pm_probability = 'Fortschritt';
$pm_yours_only = 'Selbst';
$pm_description = 'Beschreibung';

$pm_no_projects = 'Keine Projekte gefunden.';
?>
