<?php
//Uncomment this line in new translations!
//require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'You entered an invalid time period';
$pm_add_hours_success = 'Data as entered below was saved successfully';
$pm_already_booked = 'You have already booked in this period';
$pm_new_entry = 'New entry at';
$pm_fees = 'Fees';
$pm_new_fee = 'New fee';
$pm_users = 'Users';
$pm_materials = 'Materials';
$pm_new_material = 'New material';
$pm_project_data = 'Projectdata from';
$pm_load= 'Load';
$pm_enter_data = 'Enter data';
$pm_value = 'Value';
$pm_too_old = 'You are not allow to enter data older then one week';

$pm_task = 'Tasks';

$pm_employee = 'Project Manager';
$pm_project = 'Project';
$pm_starttime = 'Starting time';
$pm_endtime = 'Ending time';
$pm_breaktime = 'Break time';
$pm_this_week = 'Entered this week';
$pm_no_projects = 'You don\'t have any projects';
$pm_hours = 'Hours';
$pm_total_hours = 'Total number of hours';
$pm_client = 'Client';
$pm_created_at = 'Created at';

$pm_show_all = 'Show all';
$pm_show_period = 'Show from';
$pm_to = 'to';
$pm_show_month = 'Show month';

$pm_total_hours_days = 'Total number of hours/days';
$pm_projects_count = 'project(s)';
$pm_show_data = 'Show data';
$pm_new_project = 'New project';
$pm_other_contacts = 'Other contacts';
$pm_no_contacts = 'You don\'t have a contact that can function as a client for this project. Please create one first';

$pm_unit_value = 'Unit value';
$pm_units = 'Units';
$pm_mins = 'mins';
$pm_no_fees = 'There are no fees created yet. Only a user with administrator privileges can create fees.';
$pm_fee = 'Fee';
$pm_no_contact = 'None';
$pm_load_period= 'Period';
$pm_load_type= 'Only load data for';
$pm_total_fee = 'Total fee';
$pm_total_days = 'Total days';
$pm_total_units = 'Total units';
$pm_summary = 'Summary';
$pm_this_entry = 'this booking';
$pm_entry = 'booking';
//translation required
$pm_timer_started_at = 'Timer started at';
$pm_start_timer = 'Clock in';
$pm_stop_timer = 'Clock out';

$pm_start_date = 'Start date';
$pm_end_date = 'End date';
$pm_responsible = 'Responsible';
$pm_status = 'Status';
$pm_category = 'Category';
$pm_process_template = 'Process template';
$pm_new_category = 'New Category';

$pm_status_values[0] = 'Discontinued';
$pm_status_values[1] = 'Offer';
$pm_status_values[2] = 'Signed';
$pm_status_values[3] = 'Implementing';
$pm_status_values[4] = 'Done';
$pm_status_drop = 'Discontinued';
$pm_status_done = 'Done';
$pm_status_begin = 'Begin';
$pm_status_running = 'Running';

$pm_filter = 'Filter';
$pm_project_exists = 'A project with this name already exists';

$pm_clocked_in = 'You are clocked in. Click here if you want to clock out';

$pm_alert = 'This project is over due';
$pm_budget = 'Budget';
$pm_probability = 'Probability';
$pm_progress = 'Progress';
$pm_yours_only = 'Yourself';
$pm_description = 'Description';

$pm_no_projects = 'No projects found.';

$pm_days = 'days';
$pm_delay = 'Delay';
$pm_remain = 'Remain';

$pm_task_status_values[0] = 'Bypass';
$pm_task_status_values[1] = 'Done';
$pm_task_status_values[2] = 'Ongoing';
$pm_task_status_values[3] = 'Waiting';

$pm_task_order = '#';
$pm_task_name = 'Task name';
$pm_task_person = 'Responsibility';
$pm_task_predecessors = 'Predecessors';
$pm_task_days = 'Days';
$pm_task_status = 'Status';
$pm_task_approved = 'Check';
$pm_task_document = 'Doc';
$pm_task_level = 'Level';

$pm_task_comments = 'Comments';
$pm_task_new_comments = 'Type new comments here';

$pm_legend_planning = 'Planning';
$pm_legend_ongoing = 'Ongoing';
$pm_legend_done = 'Done';

$cmdGantt = 'Gantt chart';
$cmdDrop = 'Discontinue';
$cmdRecover = 'Recover';

$pm_ConfirmDrop = 'Are you sure you want to discontinue this project?';
$pm_ConfirmRecover = 'Are you sure you want to recover this project?';
$pm_ConfirmDeleteStatus = 'Are you sure you want to delete status \"%s\"?';
$pm_ConfirmDeleteCategory = 'Are you sure you want to delete project category ';
$pm_ConfirmDeleteTemplate = 'Are you sure you want to delete process template ';
$pm_DeleteCategory = 'Delete';
$pm_CannotDelete = 'Cannot delete this project category, there are some projects using it';
$pm_CategoryExists = "Category with name '%s' is already exists";
$pm_EditCategory = 'Rename category:';
$pm_AddCategory = 'Add new category:';
$pm_EditTemplate = 'Rename process template: ';
$pm_AddTemplate = 'Add process template:';

$strReadRights = 'Monitors';
$strWriteRights = 'Members';
?>
