<?php
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Ud. ingreso un periodo de tiempo inv&aacute;lido';
$pm_add_hours_success = 'Los datos han sido grabados satisfactoriamente';
$pm_already_booked = 'Ud. ya tiene una sesi&oacute;n abierta ahora';
$pm_new_entry = 'Entrada nueva en';
$pm_fees = 'costos';
$pm_new_fee = 'nuevo costo';
$pm_users = 'usuarios';
$pm_materials = 'materiales';
$pm_new_material = 'nuevo material';
$pm_project_data = 'Datos proyectados desde';
$pm_load= 'llamado';
$pm_enter_data = 'entre los datos';
$pm_value = 'Valor';
$pm_too_old = 'Ud. no puede entrar datos para una semana anterior';

$pm_employee = 'Empleo';
$pm_project = 'Proyecto';
$pm_starttime = 'Tiempo inicial';
$pm_endtime = 'Tiempo final';
$pm_breaktime = 'Tiempo cortado';
$pm_this_week = 'Semana completa';
$pm_no_projects = 'Ud. no tiene ning&uacute;n proyecto';
$pm_hours = 'Horas';
$pm_total_hours = 'N&uacute;mero Total de horas';
$pm_client = 'Cliente';
$pm_created_at = 'Creado en';

$pm_show_all = 'Muestre todo';
$pm_show_period = 'Muestre desde';
$pm_to = 'a';
$pm_show_month = 'Muestre mes';

$pm_total_hours_days = 'N&uacute;mero Total de horas/d&iacute;as';
$pm_projects_count = 'proyecto(s)';
$pm_show_data = 'muestre datos';
$pm_new_project = 'proyecto nuevo';
$pm_other_contacts = 'Otros contactos';
$pm_no_contacts = 'Ud. no tiene un contacto que pueda accesar esta funci&oacute;n como cliente para este proyecto. Por favor cree uno primero';

$pm_unit_value = 'Valor Unitario';
$pm_units = 'Unidades';
$pm_mins = 'mins';
$pm_no_fees = 'No existen costos creados. Unicamente el administrador tiene privilegios para crear costos.';
$pm_fee = 'Costo';
$pm_no_contact = 'Ninguno';
$pm_load_period= 'Periodo';
$pm_load_type= 'Llamar datos desde';
$pm_total_fee = 'Costo Total';
$pm_total_days = 'Total d&iacute;as';
$pm_total_units = 'Total unidades';
$pm_summary = 'Res&uacute;men';

?>
