<?php
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Vous avez entré une période horaire invalide';
$pm_add_hours_success = 'Les données entrées ci-dessous ont été enregistrées avec succès';
$pm_already_booked = 'Vous avez déjà réservé dans cette période';
$pm_new_entry = 'Nouvelle entrée à';
$pm_fees = 'honoraires';
$pm_new_fee = 'nouvel honoraire';
$pm_users = 'utilisateur';
$pm_materials = 'matériaux';
$pm_new_material = 'nouveau matériau';
$pm_project_data = 'Données du projet de';
$pm_load= 'charger';
$pm_enter_data = 'entrer les données';
$pm_value = 'Valeur';
$pm_too_old = 'Vous n\'êtes pas autorisé à entrez des données de plus d\'une semaine';

$pm_employee = 'Employé';
$pm_project = 'Projet';
$pm_starttime = 'Heure de début';
$pm_endtime = 'Heure de fin';
$pm_breaktime = 'Temps de coupure';
$pm_this_week = 'Entrées cette semaine';
$pm_no_projects = 'Vous n\'avez pas de projet';
$pm_hours = 'HEures';
$pm_total_hours = 'Nombre total d\'heures';
$pm_client = 'Client';
$pm_created_at = 'Crée à';

$pm_show_all = 'Tout voir';
$pm_show_period = 'Voir depuis';
$pm_to = 'à';
$pm_show_month = 'Voir le mois';

$pm_total_hours_days = 'Nombre toal d\'heure/jours';
$pm_projects_count = 'projet(s)';
$pm_show_data = 'voir les données';
$pm_new_project = 'nouveau projet';
$pm_other_contacts = 'Autres contacts';
$pm_no_contacts = 'Vous n\'avez pas de contact qui puisse fonctionner comme client pour ce projet. Veuillez en créer un';

$pm_unit_value = 'Valeur de l\'unité';
$pm_units = 'Unités';
$pm_mins = 'mins';
$pm_no_fees = 'Il n\'y a pas encore d\'honoraires de crées. Seul un utilisateur avec des privilèges d\'administrateur peut créer des honoraires.';
$pm_fee = 'Honoraire';
$pm_no_contact = 'Aucun';
$pm_load_period= 'Période';
$pm_load_type= 'Charger les données pour';
$pm_total_fee = 'Total des honoraires';
$pm_total_days = 'Total des jours';
$pm_total_units = 'Total des unités';
$pm_summary = 'Sommaire';
$pm_this_entry = 'Cette réservation';
$pm_entry = 'Réservation';
//translation required
$pm_timer_started_at = 'L\'alarme démarre à';
$pm_start_timer = 'Démarrer l\'alarme';
$pm_stop_timer = 'Arrêter l\'alarme';

$pm_start_date = 'Date de début';
$pm_end_date = 'Date de fin';
$pm_responsible = 'Responsable';
$pm_status = 'Statut';

$pm_status_values[1] = 'Proposition';
$pm_status_values[2] = 'En cours';
$pm_status_values[3] = 'En attente';
$pm_status_values[4] = 'Fait';
$pm_status_values[5] = 'Facturé';

$pm_filter = 'Filtre';
$pm_project_exists = 'Un projet avec ce nom existe déjà';

$pm_clocked_in = 'You are clocked in. Click here if you want to clock out';

$pm_alert = 'Ce projet est proche de l\'expiration';
$pm_budget = 'Budget';
$pm_probability = 'Probabilité';
$pm_yours_only = 'Vous-même';
$pm_description = 'Description';

$pm_no_projects = 'Aucuns projets trouvés.';
?>