<?php
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'U heeft een ongeldige datum ingevoerd.';
$pm_add_hours_success = 'Onderstaande data is succesvol ingevoerd.';
$pm_already_booked = 'U heeft al uren geboekt in deze periode';
$pm_new_entry = 'Nieuwe invoer voor';
$pm_fees = 'Tarieven';
$pm_new_fee = 'Nieuw tarief';
$pm_users = 'Gebruikers';
$pm_materials = 'Materialen';
$pm_new_material = 'Nieuw materiaal';
$pm_project_data = 'Projectgegevens van';
$pm_load= 'Laden';
$pm_enter_data = 'Invoeren';
$pm_value = 'Waarde';
$pm_too_old = 'U mag geen boekingen plaatsen ouder dan een week';

$pm_employee = 'Werknemer';
$pm_project = 'Project';
$pm_starttime = 'Starttijd';
$pm_endtime = 'Eindtijd';
$pm_breaktime = 'Pauzetijd';
$pm_this_week = 'Afgelopen week ingevoerd';
$pm_no_projects = 'U heeft nog geen projecten';
$pm_hours = 'Uren';
$pm_total_hours = 'Totaal aantal uren';
$pm_client = 'Klant';
$pm_created_at = 'Gemaakt op';

$pm_show_all = 'Toon alles';
$pm_show_period = 'Toon periode van';
$pm_to = 'tot';
$pm_show_month = 'Toon maand';

$pm_total_hours_days = 'Totaal aantal uren/dagen';
$pm_projects_count = 'project(en)';
$pm_show_data = 'Toon data';
$pm_new_project = 'Nieuw project';
$pm_other_contacts = 'Overige contactpersonen';
$pm_no_contacts = 'U heeft nog geen contactpersoon die als klant kan dienen voor dit project. Maak deze eerst aan.';

$pm_unit_value = 'Eenheid waarde';
$pm_units = 'Eenheden';
$pm_mins = 'min';
$pm_no_fees = 'Er zijn nog geen tarieven ingevoerd. Maak eerst tarieven aan. U heeft schrijfrechten voor deze module nodig om tarieven aan te kunnen maken.';
$pm_fee = 'Tarief';
$pm_no_contact = 'Geen';
$pm_load_period= 'Periode';
$pm_load_type= 'Alleen uren tonen voor';
$pm_total_fee = 'Totaal tarief';
$pm_total_days = 'Totaal aantal dagen';
$pm_total_units = 'Totaal aantal eenheden';
$pm_summary = 'Samenvatting';

$pm_this_entry = 'deze invoer';
$pm_entry = 'invoer';
$pm_timer_started_at = 'Timer is gestart op';
$pm_start_timer = 'Inklokken';
$pm_stop_timer = 'Uitklokken';

//
$pm_start_date = 'Start datum';
$pm_end_date = 'Eind datum';
$pm_responsible = 'Verantwoordelijke';
$pm_status = 'Status';

$pm_status_values[1] = 'Offerte';
$pm_status_values[2] = 'Lopend';
$pm_status_values[3] = 'Wachtend';
$pm_status_values[4] = 'Klaar';
$pm_status_values[5] = 'Gefactureerd';

$pm_filter = 'Filter';
$pm_project_exists = 'Er bestaat al een project met deze naam';

$pm_alert = 'Dit project had al af moeten zijn';

$pm_clocked_in = 'U bent ingeklokt. Klik hier als u wilt uitklokken';
$pm_budget = 'Budget';
$pm_probability = 'Waarschijnlijkheid';

$pm_yours_only = 'Uwzelf';
$pm_description = 'Omschrijving';

$pm_no_projects = 'Geen projecten gevonden.';
?>