<?php
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Você introduziu um período de tempo inválido';
$pm_add_hours_success = 'Os dados inseridos abaixo foram salvos com sucesso';
$pm_already_booked = 'Você já reservou este período';
$pm_new_entry = 'Nova entrada em';
$pm_fees = 'Taxas';
$pm_new_fee = 'Nova taxa';
$pm_users = 'Usuários';
$pm_materials = 'Materiais';
$pm_new_material = 'Novo material';
$pm_project_data = 'Data do projeto de';
$pm_load= 'Carregar';
$pm_enter_data = 'Introduzir dados';
$pm_value = 'Valor';
$pm_too_old = 'Você não pode introduzir dados mais velhos que uma semana';
$pm_employee = 'Empregado';
$pm_project = 'Projeto';
$pm_starttime = 'Tempo de início';
$pm_endtime = 'Tempo de conclusão';
$pm_breaktime = 'Tempo de espera';
$pm_this_week = 'Introduzido nesta semana';
$pm_no_projects = 'Você não tem nenhum projeto';
$pm_hours = 'Horas';
$pm_total_hours = 'Número total de horas';
$pm_client = 'Cliente';
$pm_created_at = 'Criado em';
$pm_show_all = 'Mostrar tudo';
$pm_show_period = 'Mostrar de';
$pm_to = 'a';
$pm_show_month = 'Mostrar mês';
$pm_total_hours_days = 'Número total de horas/dias';
$pm_projects_count = 'Projeto(s)';
$pm_show_data = 'Mostrar dados';
$pm_new_project = 'Novo Projeto';
$pm_other_contacts = 'Outros contatos';
$pm_no_contacts = 'Você não tem um contato que pode funcionar como cliente para este projeto. Por favor crie um contato antes e tente novamente.';
$pm_unit_value = 'Valor de unidade';
$pm_units = 'Unidades';
$pm_mins = 'Minutos';
$pm_no_fees = 'As taxas ainda não existem ou não foram criadas. Somente um usuário com privilégios administrativos pode criar taxas.';
$pm_fee = 'Taxa';
$pm_no_contact = 'Nenhum';
$pm_load_period= 'Período';
$pm_load_type= 'Carregar dados por';
$pm_total_fee = 'Valor Total';
$pm_total_days = 'Total de Dias';
$pm_total_units = 'Total de Unidades';
$pm_summary = 'Sumário';

$pm_this_entry = 'este registro';
$pm_entry = 'registro';
//translation required
$pm_timer_started_at = 'Marcador de Tempo inicia em';
$pm_start_timer = 'Iniciar Marcador de Tempo';
$pm_stop_timer = 'Para Marcador de Tempo';

$pm_start_date = 'Data de início';
$pm_end_date = 'Data de término';
$pm_responsible = 'Responsável';
$pm_status = 'Situação';

$pm_status_values[1] = 'Projeto';
$pm_status_values[2] = 'Em andamento';
$pm_status_values[3] = 'Aguardando';
$pm_status_values[4] = 'Pronto';
$pm_status_values[5] = 'Finalizado';

$pm_filter = 'Filtro';
$pm_project_exists = 'Um projeto com este nome já existe';

$pm_clocked_in = 'Você está marcando o tempo. Clique aqui para parar';

$pm_alert = 'Este projeto está acima do estipulado';
$pm_budget = 'Orçamento';
$pm_probability = 'Probabilidade';
$pm_yours_only = 'Meus dados';
$pm_description = 'Descrição';

$pm_no_projects = 'Nenhum projeto encontrado.';
?>
