<?php
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Du angav en felaktig tidsperiod';
$pm_add_hours_success = 'Data som angavs nedanför sparades';
$pm_already_booked = 'Du har redan bokat i denna period';
$pm_new_entry = 'Nytt inlägg på';
$pm_fees = 'avgift';
$pm_new_fee = 'ny avgift';
$pm_users = 'användare';
$pm_materials = 'material';
$pm_new_material = 'nytt material';
$pm_project_data = 'Projektdata från';
$pm_load= 'ladda';
$pm_enter_data = 'ange data';
$pm_value = 'Värde';
$pm_too_old = 'Det är inte möjligt att lägga in data som är äldre en en vecka';

$pm_employee = 'Anställd';
$pm_project = 'Projekt';
$pm_starttime = 'Starttid';
$pm_endtime = 'Slutttid';
$pm_breaktime = 'Rasttid';
$pm_this_week = 'Inskrivet denna vecka';
$pm_no_projects = 'Du har inga projekt';
$pm_hours = 'Timmar';
$pm_total_hours = 'Totalt antal timmar';
$pm_client = 'Klient';
$pm_created_at = 'Skapad';

$pm_show_all = 'Visa alla';
$pm_show_period = 'Visa från';
$pm_to = 'till';
$pm_show_month = 'Visa månad';

$pm_total_hours_days = 'Totalt antal av timmar/dagar';
$pm_projects_count = 'projekt';
$pm_show_data = 'visa data';
$pm_new_project = 'nytt projekt';
$pm_other_contacts = 'Andra kontakter';
$pm_no_contacts = 'Du har ingen kontakt som kan fungera som en klient för detta projekt. Var god skapa en först';

//translation required
$pm_unit_value = 'Enhetspris';
$pm_units = 'Enheter';
$pm_mins = 'minuter';
$pm_no_fees = 'Inga avgifter är skapade ännu. Endast en användare med administratörsrättigheter kan skapa detta.';
$pm_fee = 'Avgift';
$pm_no_contact = 'Ingen';
$pm_load_period= 'Period';
$pm_load_type= 'Ladda data för';
$pm_total_fee = 'Total avgift';
$pm_total_days = 'Total dagar';
$pm_total_units = 'Total enheter';
$pm_summary = 'Summa';
?>
