<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'Egenskaber';
$admin_modules = 'Moduler';
$strPath = 'Sti';
$admin_invalid_path = 'Du har indtastet en ugyldig sti';
$admin_overview = 'Oversigt';
$admin_module = 'Modul';
$admin_modules_text = 'Vælg de moduler du vil anvende og klik på \''.$cmdSave.'\'.<br />Klik på aktive moduler for at ændre tilladelser.';
$admin_bookmarks_text = 'Opret bogmærker her, som automatisk tilføjes når du opretter en ny bruger.';
$admin_bookmark_new_window = 'Åben bogmærke i nyt vindue';
$admin_menus_text = "Marker de(n) menu(er) som du vil bruge og klik på 'Gem'";
$admin_start_module = 'Start Group-Office i';
$admin_menus = "menuer";
$admin_formats = "datoformater";
$admin_date_formats_text = 'Tilføj datoformater i <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> med en beskrivelse og klik på Ok.';
?>
