<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'Proprietà';
$admin_modules = 'Moduli';
$strPath = 'Percorso';
$admin_invalid_path = 'Hai inserito un percorso non valido';
$admin_overview = 'Sommario';
$admin_module = 'Modulo';
$admin_modules_text = 'Scegli i moduli che vuoi utilizzare e seleziona \''.$cmdSave.'\'.<br />Seleziona i moduli attivi per cambiargli i permessi.';
$admin_bookmarks_text = 'Aggiungi qui i segnalibri che saranno creati automaticamente con la registrazione di un nuovo utente.';

$admin_bookmark_new_window = 'Apri il segnalibro in una nuova finestra';
$admin_menus_text = "Seleziona i menù che vuoi utilizzare e premi 'salva'";
$admin_start_module = 'Inizia Group-Office con';
$admin_menus = "Menù";
$admin_formats = "Formato data";
$admin_date_formats_text = 'Aggiungi le date in <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">formato PHP</a> con una descrizione e premi Ok.';

//2.05
$strAuthors = 'Autore/i';
$strVersion = 'Versione';
$strReleaseDate = 'Data release';
$strDescription = 'Descrizione';
$strStatus = 'Stato';
$strNoModuleInfo = 'Nessuna infomarazione sul modulo disponibile';

$cmdInstall = 'Installa';
$cmdUninstall = 'Disinstalla';
$strConfirmUninstallPrefix = 'Sei sicuro di volere disinstallare';
$strConfirmUninstallSuffix = '?';
?>
