<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'Đặc tính';
$admin_modules = 'Các chức năng';
$strPath = 'Đường dẫn';
$admin_invalid_path = 'Bạn nhập sai đường dẫn';
$admin_overview = 'Sơ lược';
$admin_module = 'Chức năng';
$admin_modules_text = 'Nhấn vào Cài đặt hoặc Gỡ bỏ. Chú ý, việc gỡ bỏ một module sẽ gỡ bỏ tất cả dữ liệu liên quan!';
$admin_bookmarks_text = 'Thêm đánh dấu trang tại đây sẽ tự động tạo khi bạn đăng ký người dùng mới.';
$admin_bookmark_new_window = 'Mở đánh dấu trang trong cửa sổ mới';
$admin_menus_text = "Chọn vào trình đơn bạn muốn dùng và nhấn 'Lưu'";
$admin_start_module = 'Bắt đầu HPT-OBM với';
$admin_menus = "Menu's";
$admin_formats = "Đinh dạng ngày";
$admin_date_formats_text = 'Thêm định dạng ngày theo <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">đinh dạng của PHP</a> với mô tả và nhấn Ok.';

//2.05
$strAuthors = 'Tác giả';
$strVersion = 'Phiên bản';
$strReleaseDate = 'Ngày phát hành';
$strDescription = 'Mô tả';
$strStatus = 'Trạng thái';
$strNoModuleInfo = 'Không có thông tin về Chức năng này';

$cmdInstall = 'Cài đặt';
$cmdUninstall = 'Gỡ bỏ';
$strConfirmUninstallPrefix = 'Bạn có chắc là bạn muốn gỡ bỏ';
$strConfirmUninstallSuffix = '?';

?>
