<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'Eigenschaften';
$admin_modules = 'Module';
$strPath = 'Pfad';
$admin_invalid_path = 'Der eingegebene Pfad ist ung&uuml;ltig';
$admin_overview = '&Uuml;bersicht';
$admin_module = 'Modul';
$admin_modules_text = 'Bitte die zu aktivierenden Module w&auml;hlen und auf \'Installieren\' klicken.<br />In einem installierten Modul auf \'Berechtigungen\' klicken, um die Berechtigungen zu &auml;ndern.';
$admin_bookmarks_text = 'Bitte hier Lesezeichen anlegen, die allen neu angelegten Benutzern zur Verf&uuml;gung gestellt werden sollen.';
$admin_bookmark_new_window = 'Oeffne Lesezeichen in einem neuen Fenster';
$admin_menus_text = "Bitte die zu aktivierenden Men&uuml;-Eintr&auml;ge ausw&auml;hlen und auf 'speichern' klicken";
$admin_start_module = 'Starte Group-Office mit';
$admin_menus = "Men&uuml;s";
$admin_formats = "Datumsformate";
$admin_date_formats_text = 'Bitte ein Datumsformat im <a class="normal" target="_blank" href="http://www.php.net/manual/de/function.date.php">PHP-Format</a> definieren und mit ok best&auml;tigen.';

//2.05
$strAuthors = 'Author(en)';
$strVersion = 'Version';
$strReleaseDate = 'Ver&ouml;ffentlichungsdatum';
$strDescription = 'Beschreibung';
$strStatus = 'Status';
$strNoModuleInfo = 'Keine Modulinformation verf&uuml;gbar';

$cmdInstall = 'Installieren';
$cmdUninstall = 'Deinstallieren';
$strConfirmUninstallPrefix = 'Sind Sie sicher, dass Sie das Modul';
$strConfirmUninstallSuffix = 'deinstallieren möchten?';
?>
