<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'propiedades';
$admin_modules = 'm&oacute;dulos';
$strPath = 'ruta';
$admin_invalid_path = 'Ud. ha ingresado una ruta inv&aacute;lida';
$admin_overview = 'Vistazo';
$admin_module = 'M&oacute;dulo';
$admin_modules_text = 'Seleccione los m&oacute;dulos que desea hacer visibles y haga click en \''.$cmdSave.'\'.<br /> Haga click en los m&oacute;dulos activos para cambiar sus permisos.';
$admin_bookmarks_text = 'A&ntilde;ada los favoritos que ser&aacute;n puestos autom&aacute;ticamente cuando un usuario nuevo sea creado.';
$admin_bookmark_new_window = 'Abrir favoritos en una ventana nueva';
$admin_menus_text = "Seleccione los men&uacute; que desea que aparezcan y haga click en 'Grabar'";
$admin_start_module = 'Iniciar Group-Office en';
$admin_menus = "men&uacute;s";
$admin_formats = "formato de fecha";
$admin_date_formats_text = 'A&ntilde;ada los formatos de fecha en <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">formato PHP</a> Con una descripcion y haga click en Ok.';
?>
