<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'Eigenschappen';
$admin_modules = 'Modules';
$strPath = 'Pad';
$admin_invalid_path = 'U heeft een ongeldig pad ingevoerd';
$admin_module = 'Module';
$admin_overview = 'Overzicht';
$admin_modules_text = 'Klik op Installeren of Deinstalleren. Let op, Alle module gegevens worden verwijderd bij een deinstallatie!';

$admin_bookmarks_text = 'Plaats hier bladwijzer die automatisch worden toegevoegd aan een nieuwe gebruiker.';
$admin_bookmark_new_window = 'Open bladwijzer in een nieuw venster';
$admin_menus_text = "Selecteer de gewenste menu's";
$admin_start_module = 'Start Group-Office in';
$admin_menus = "Menu's";
$admin_formats = "Datum formaten";
$admin_date_formats_text = 'Voeg datum formaten toe in <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP formaat</a> met een beschrijving en klik op \'Ok\'.';
//2.05
$strAuthors = 'Auteur(s)';
$strVersion = 'Versie';
$strReleaseDate = 'Release datum';
$strDescription = 'Beschrijving';
$strStatus = 'Status';
$strNoModuleInfo = 'Geen module informatie beschikbaar';

$cmdInstall = 'Installeren';
$cmdUninstall = 'Deinstalleren';

$strConfirmUninstallPrefix = 'Weet u zeker dat u';
$strConfirmUninstallSuffix = 'wilt deinstaleren?';
?>
