<?php
//Uncomment this line in new translations!
//require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'Lastnosti';
$admin_modules = 'Moduli';
$strPath = 'Pot';
$admin_invalid_path = 'Vnesli ste napaèno pot';
$admin_overview = 'Pregled';
$admin_module = 'Modul';
$admin_modules_text = 'Izberite module, ki jih ¾elite uporabiti in kliknite na \''.$cmdSave.'\'.<br />Kliknite na aktivne module, da spremenite njihova dovoljenja.';
$admin_bookmarks_text = 'Sem vnesite zaznamke, ki bodo samodejno ustvarjeni ob registraciji novega uporabnika.';
$admin_bookmark_new_window = 'Odpri zaznamek v novem oknu';
$admin_menus_text = "Preverite meni, ki ga ¾elite uporabiti in kliknite na 'shrani'";
$admin_start_module = 'Za¾eni Group-Office v';
$admin_menus = "Meniji";
$admin_formats = "Oblika datumov";
$admin_date_formats_text = 'Dodaj oblike datumov v <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP obliki</a> z opisom in kliknite na v redu.';

//2.05
$strAuthors = 'Avtor(ji)';
$strVersion = 'Razlièica';
$strReleaseDate = 'Datum izdaje';
$strDescription = 'Opis';
$strDescription = 'Opis';
$strStatus = 'Status';
$strNoModuleInfo = 'Informacije o modulu niso na voljo';

$cmdInstall = 'Namesti';
$cmdUninstall = 'Odstrani';
$strConfirmUninstallPrefix = 'Ali ste preprièani, da ¾elite odstranit';
$strConfirmUninstallSuffix = '?';

?>
