<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$admin_properties = 'egenskaper';
$admin_modules = 'moduler';
$strPath = 'Sögväg';
$admin_invalid_path = 'Du angav en felaktig sökväg';
$admin_overview = 'överblick';
$admin_module = 'Modul';
$admin_modules_text = 'Välj de moduler du vill använda och klicka på \''.$cmdSave.'\'.<br />Klicka på aktivera moduler för att ändra deras rättigheter.';

$admin_bookmarks_text = 'Lägg till bokmärken här som automatiskt skapas till ett nytt användarkonto.';
$admin_bookmark_new_window = 'Öppna bokmärke i ett nytt fönster.';
$admin_menus_text = "Markera menyerna du önskar använda och tryck på 'Spara'";
$admin_start_module = 'Starta Group-Office i';
$admin_menus = "meny'er";
$admin_formats = "datumformat";
$admin_date_formats_text = 'Lägg till datumformat i <a class="normal" target="_blank"
href="http://www.php.net/manual/en/function.date.php">PHP format</a> med en beskrivning och klicka på Ok.';
?>
