<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = 'Системна бележка';
$si_hostname = 'Име на госта';
$si_ip = 'IP-адрес';
$si_kernel = 'Kернел версия';
$si_web_server = 'Уеб сървър';
$si_php_version = 'PHP версия';
$si_uptime = 'Uptime';
$si_users = 'Текущи потребители';
$si_average_load = 'Средно зареждане';
$si_days = 'дни';
$si_hours = 'часове';
$si_mins = 'минути';

$si_hardware_summary = 'Хардуерен преглед';
$si_processors = 'Процесори';
$si_model = 'Модел';
$si_clock = 'Clock frequentie';
$si_buffersize = 'Големина на буфера';
$si_bogomips = 'System bogomips';
$si_pci = 'PCI приспособления';
$si_ide = 'IDE приспособления';
$si_scsi = 'SCSI приспособления';
$si_capacity = 'Капацитет';

$si_network_use = 'Използваемост на мрежата';
$si_device = 'Приспособление';
$si_recieved = 'Получено';
$si_sent = 'Изпратено';
$si_error = 'Err/Drop';


$si_memory_use = 'Използваемост на паметта';
$si_type = 'Вид';
$si_percentage_used = 'Използвани проценти';
$si_free = 'Свободно';
$si_used = 'Използвано';
$si_size = 'Размер';
$si_physical = 'Физическа памет';
$si_swap = 'Сменяема памет';

$si_filesystems = 'Mounted filesystems';
$si_mount_point = 'Mount point';
$si_partition = 'Деление';
$si_total = 'Общо';
$si_show_phpinfo = 'PHP конфигурация';
?>
