<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = 'System-Zusammenfassung';
$si_hostname = 'Rechnername';
$si_ip = 'IP-Adresse';
$si_kernel = 'Kernel Version';
$si_web_server = 'Web Server';
$si_php_version = 'PHP Version';
$si_uptime = 'Uptime';
$si_users = 'Angemeldete Benutzer';
$si_average_load = 'Average load';
$si_days = 'Tage';
$si_hours = 'Stunden';
$si_mins = 'Minuten';

$si_hardware_summary = 'Hardware-&Uuml;bersicht';
$si_processors = 'Prozessoren';
$si_model = 'Modell';
$si_clock = 'Taktfrequenz';
$si_buffersize = 'Puffergr&ouml;sse ';
$si_bogomips = 'System bogomips';
$si_pci = 'PCI Ger&auml;te';
$si_ide = 'IDE Ger&auml;te';
$si_scsi = 'SCSI Ger&auml;te';
$si_capacity = 'Kapazit&auml;t';

$si_network_use = 'Netzwerkauslastung';
$si_device = 'Ger&auml;t';
$si_recieved = 'Empfangen';
$si_sent = 'Gesendet';
$si_error = 'Fehler/Verworfen';


$si_memory_use = 'Speicherauslastung';
$si_type = 'Typ';
$si_percentage_used = 'Prozentuale Auslastung';
$si_free = 'Frei';
$si_used = 'Belegt';
$si_size = 'Gr&ouml;sse';
$si_physical = 'Physischer Speicher';
$si_swap = 'Auslagerungsspeicher';

$si_filesystems = 'Eingebundene Dateisysteme';
$si_mount_point = 'Mount-Punkt';
$si_partition = 'Partition';
$si_total = 'Gesamt';
$si_show_phpinfo = 'PHP Konfiguration';
?>