<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = 'Res&uacute;men del Sistema';
$si_hostname = 'Nombre m&aacute;quina';
$si_ip = 'Direcci&oacute;n IP';
$si_kernel = 'Versi&oacute;n Kernel';
$si_web_server = 'Servidor Web';
$si_php_version = 'Versi&oacute;n PHP';
$si_uptime = 'Uptime';
$si_users = 'Usuarios Actuales';
$si_average_load = 'Promedio de Carga';
$si_days = 'd&iacute;as';
$si_hours = 'horas';
$si_mins = 'minutos';

$si_hardware_summary = 'Vistazo al Hardware';
$si_processors = 'Procesadores';
$si_model = 'Modelo';
$si_clock = 'Fecuencia del Reloj';
$si_buffersize = 'Tama&ntilde;o del Buffer';
$si_bogomips = 'Sistema Bogomips';
$si_pci = 'Dispositivos PCI';
$si_ide = 'Dispositivos IDE';
$si_scsi = 'Dispositivos SCSI';
$si_capacity = 'Capacidad';

$si_network_use = 'Uso de Red';
$si_device = 'Dispositivo';
$si_recieved = 'Recibido';
$si_sent = 'Enviado';
$si_error = 'Err/Drop';


$si_memory_use = 'Uso de Memoria';
$si_type = 'Tipo';
$si_percentage_used = 'Porcentaje Usado';
$si_free = 'Libre';
$si_used = 'Usada';
$si_size = 'Tama&ntilde;o';
$si_physical = 'Memoria F&iacute;sica';
$si_swap = 'Memoria Swap';

$si_filesystems = 'Filesystems montados';
$si_mount_point = 'Punto de Montaje';
$si_partition = 'Partici&oacute;n';
$si_total = 'Total';
$si_show_phpinfo = 'Configuraci&oacute;n PHP';
?>
