<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = 'Systeem overzicht';
$si_hostname = 'Hostnaam';
$si_ip = 'IP-adres';
$si_kernel = 'Kernel versie';
$si_web_server = 'Web server';
$si_php_version = 'PHP versie';
$si_uptime = 'Uptime';
$si_users = 'Huidige gebruikers';
$si_average_load = 'Gemiddelde belasting';
$si_days = 'dagen';
$si_hours = 'uren';
$si_mins = 'minuten';

$si_hardware_summary = 'Hardware overzicht';
$si_processors = 'Processors';
$si_model = 'Model';
$si_clock = 'Kloksnelheid';
$si_buffersize = 'Buffergrootte';
$si_bogomips = 'Systeem Bogomips';
$si_pci = 'PCI Apparaten';
$si_ide = 'IDE Apparaten';
$si_scsi = 'SCSI Apparaten';
$si_capacity = 'Capaciteit';

$si_network_use = 'Netwerkgebruik';
$si_device = 'Apparaat';
$si_recieved = 'Ontvangen';
$si_sent = 'Verzonden';
$si_error = 'Err/Drop';


$si_memory_use = 'Geheugengebruik';
$si_type = 'Type';
$si_percentage_used = 'Percentage gebruikt';
$si_free = 'Vrij';
$si_used = 'Gebruikt';
$si_size = 'Grootte';
$si_physical = 'Fysiek geheugen';
$si_swap = 'Swap geheugen';

$si_filesystems = 'Aangesloten bestandssystemen';
$si_mount_point = 'Mount point';
$si_partition = 'Partitie';
$si_total = 'Totaal';
$si_show_phpinfo = 'PHP configuratie';
?>