<?php
require($GO_LANGUAGE->get_fallback_base_language_file('modules'));

$si_system_summary = 'Sum&aacute;rio do sistema';
$si_hostname = 'Nome do servidor';
$si_ip = 'Endere&ccedil;o IP';
$si_kernel = 'Vers&atilde;o de Kernel';
$si_web_server = 'Servidor de Web';
$si_php_version = 'Vers&atilde;o de PHP';
$si_uptime = 'Tempo ao vivo';
$si_users = 'Utilizadores atuais';
$si_average_load = 'Carga m&eacute;dia';
$si_days = 'dias';
$si_hours = 'horas';
$si_mins = 'minutos';

$si_hardware_summary = 'Vista geral do Hardware';
$si_processors = 'Processadores';
$si_model = 'Modelo';
$si_clock = 'Frequ&ecirc;ncia do processador';
$si_buffersize = 'Tamanho do Buffer';
$si_bogomips = 'N&iacute;vel de bogomips neste sistema';
$si_pci = 'Aparelhos tipo PCI';
$si_ide = 'Aparelhos tipo IDE';
$si_scsi = 'Aparelhos tipo SCSI';
$si_capacity = 'Capacidade';

$si_network_use = 'Uso da rede';
$si_device = 'Aparelho';
$si_recieved = 'Recebido';
$si_sent = 'Enviado';
$si_error = 'Erros';


$si_memory_use = 'Uso da Mem&oacute;ria';
$si_type = 'Tipo';
$si_percentage_used = 'Porcentagem usada';
$si_free = 'Livre';
$si_used = 'Usada';
$si_size = 'Tamanho';
$si_physical = 'Mem&oacute;ria Física';
$si_swap = 'Mem&oacute;ria de troca';

$si_filesystems = 'Diret&oacute;rios montados';
$si_mount_point = 'Ponto da montagem';
$si_partition = 'Divis&atilde;o no disco';
$si_total = 'Total';
$si_show_phpinfo = 'Configura&ccedil;&atilde;o do PHP';
?>