<?php
require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = '系統摘要';
$si_hostname = '主機名稱';
$si_ip = '網絡位址';
$si_kernel = '核心版本';
$si_web_server = '網頁伺服器';
$si_php_version = 'PHP版本';
$si_uptime = '已起動時間';
$si_users = '當前的使用者';
$si_average_load = '平均負載';

$si_days = '日';
$si_hours = '時';
$si_mins = '分';
$si_hardware_summary = '硬件總覽';
$si_processors = '處理器';
$si_model = '型號';
$si_clock = '時脈';
$si_buffersize = '緩衝大小';
$si_bogomips = '系統 bogomips';
$si_pci = 'PCI 裝置 ';
$si_ide = 'IDE裝置';
$si_scsi = 'SCSI裝置';
$si_capacity = '容量';
$si_network_use = '網絡使用量';
$si_device = '裝置';
$si_recieved = '已接收';
$si_sent = '已送出';
$si_error = '錯誤/丟棄';
$si_memory_use = '記憶體使用量';
$si_type = '類型';
$si_percentage_used = '已使用百分比';
$si_free = '可用';
$si_used = '已使用';
$si_size = '大小';
$si_physical = '物理記憶體';
$si_swap = '交換記憶體';
$si_filesystems = '已掛載的檔案系統';
$si_mount_point = '掛載點';
$si_partition = '分割區';
$si_total = '總共';
$si_show_phpinfo = 'PHP設定值';
?>