<?php
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Bienvenido a ";
$strUseMenu = "Use el men&uacute; o haga click sobre un icono para iniciar cualquier aplicaci&oacute;n de ";
$click_to_login = "Haga click aqui para iniciar.";
$login_text = "Ingrese su nombre de usuario y clave de acceso";
$login_username = "Nombre de usuario";
$login_password = "Clave de acceso";
$login_missing_field = "Usted digit&oacute; mal su nombre de usuario o clave de acceso.";
$login_bad_login = "Error en nombre de usuario o clave de acceso";
$login_remind = "Mantenga la sesi&oacute;n hasta oprimir el boton de salir.";
$login_language = 'Idioma';
?>
