<?php
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Välkommen till ";
$strUseMenu = "Använd menyn eller klicka på snabblänkarna nedan för att börja använda ";
$click_to_login = "Tryck här för att logga in.";
$login_text = "Ange ditt loginnamn och lösenord för att logga in";
$login_username = "Användarnamn";
$login_password = "Lösenord";
$login_missing_field = "Du angav inte ditt användarnman eller lösenord.";
$login_bad_login = "Felaktigt användarnamn eller lösenord";
$login_remind = "Håll mig inloggad tills jag själv loggar ut.";
$login_language = 'Språk';
?>
