<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Chào mừng bạn đến với ";
$strUseMenu = "Dùng trình đơn hoặc nhấn lên liên kết dưới để bắt đầu dùng ";
$click_to_login = "Nhấn vào đây để đăng nhập.";
$login_text = "Nhập tài khoản và mật mã để đăng nhập";
$login_username = "Tài khoản";
$login_password = "Mật khẩu";
$login_missing_field = "Bạn chưa điền tài khoản hoặc mật khẩu.";
$login_bad_login = "Nhầm tài khoản hoặc mật khẩu";
$login_remind = "Giữ trạng thái đăng nhập cho đến khi nhấn vào thoát.";
$login_language = 'Ngôn ngữ';
$login_old_version = 'Bạn đang sử dụng một trình duyệt cũ.<br/>Vài tính năng của OBM có thể sẽ không hoạt động với trình duyệt này.<br/>Bạn nên dùng trình duyệt mới hơn.';
?>
