<?php
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Willkommen in ";
$strUseMenu = "Bitte das Menue oder die unteren Links verwenden fuer die Arbeit mit ";
$click_to_login = "Zum Anmelden hier klicken.";
$login_text = "Zum Anmelden Benutzername und Passwort eingeben";
$login_username = "Benutzername";
$login_password = "Passwort";
$login_missing_field = "Benutzername oder Passwort wurde nicht eingegeben.";
$login_bad_login = "Benutzername oder Passwort falsch";
$login_remind = "Ich moechte angemeldet bleiben bis ich mich mit logout abmelde.";
$login_language = 'Sprache';
?>
