<?php
//Uncomment this line in new translations!
//require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Welcome to ";
$strUseMenu = "Use the menu or click on the fast links below to start using ";
$click_to_login = "Click here to login.";
$login_text = "Enter your username and password to login";
$login_username = "Username";
$login_password = "Password";
$login_missing_field = "You didn't fill out your username or password.";
$login_bad_login = "Wrong username or password";
$login_remind = "Keep me logged in till I press the logout button.";
$login_language = 'Language';
$login_old_version = 'You are using an old Web browser.<br/>Some functions of OBM may not work properly with this browser.<br/>You should use a newer Web browser.';
?>
