<?php
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Bienvenue à ";
$strUseMenu = "Utilisez le menu ou cliquez sur les liens rapides ci-dessous pour commencer à utiliser ";
$click_to_login = "Cliquez içi pour vous connecter.";
$login_text = "Entrez votre nom d'utilisateur et votre mot de passe pour vous connecter";
$login_username = "Utilisateur";
$login_password = "Mot de passe";
$login_missing_field = "Vous n'avez pas rempli votre nom d'utilisateur ou votre mot de passe.";
$login_bad_login = "Mauvais nom d'utilisateur ou mot de passe";
$login_remind = "Me laisser connecter jusqu'à ce que j'appuie sur le bouton de déconnexion.";
$login_language = 'Langue';
?>
