<?php
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Benvenuto in ";
$strUseMenu = "Usa il menù o seleziona i collegamenti veloci sottostanti per iniziare ad usare ";
$click_to_login = "Click qui per connettersi.";
$login_text = "Inserire nome utente e password per connettersi";
$login_username = "Nome utente";
$login_password = "Password";
$login_missing_field = "Non hai inserito il nomeutente o la password.";
$login_bad_login = "Nome utente o password errate.";
$login_remind = "Mantieni il collegamento finché non seleziono 'disconnetti'.";
$login_language = 'Lingua';
?>
