<?php
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Welkom bij ";
$strUseMenu = "Gebruik het menu of klik op de snelkoppelingen hieronder om te starten met ";
$login_text = "Voer gebruikersnaam en wachtwoord in om in te loggen";
$login_username = "Gebruikersnaam";
$login_password = "Wachtwoord";
$login_remind = "Klik hier om ingelogd te blijven tot U op uitloggen klikt.";
$login_missing_field = "U heeft uw wachtwoord of gebruikersnaam niet ingevuld.";
$login_bad_login = "Wachtwoord of gebruikersnaam onjuist";
$login_language = 'Taal';
?>
