<?php
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Bem-vindo ao ";
$strUseMenu = "Use o menu ou clique nos ícones para começar ";
$click_to_login = "Clique aqui para iniciar uma sessão.";
$login_text = "Digite seu usuário e senha para iniciar uma sessão";
$login_username = "Usuário";
$login_password = "Senha";
$login_missing_field = "Você não digitou o seu nome de usuário ou senha.";
$login_bad_login = "Usuário ou senha errada";
$login_remind = "Mantenha-me conectado até eu indicar que quero sair.";
$login_language = 'Idioma';
?>
