<?php
require($GO_LANGUAGE->get_fallback_base_language_file('groups'));

$groups_title = "Групи потребители";
$groups_tab = "Групи";
$groups_saved = "Настройките запазени.";
$groups_text = "Натиснете на група за да видите нейните настройки.";
$groups_users_in = "Потребители в група ";
$groups_no_contacts = "Нямате контакти за избиране.<br /> Използвайте Адресника за да добавите членове към вашите контакти.";

$add_group_text = "Въведете име и натиснете 'Ok' за да добавите нова група.";
$add_group_fail = "Добавяне на групата е неуспешно. Моля опитайте отново.";
$add_group_success = "Добавяне на групата е успешно.";
$add_group_exists = "Името вече съществува. Моля изберете друго име.";
$add_group_no_name = "Не сте въвели име.";
$groups_everyone = "Тази група е специална и съдържа всички потребители. Не може да променяте тази група.";
$groups_users_in1 = "потребител(и) в група";
$groups_no_users = "Няма потребители в тази група.";
$groups_users_in_select = "Изберете потребителите които искате да добавите към тази група:";

//translation required
$groups_new_group = 'Нова група';
$groups_members = 'Членове';
?>
