<?php
require($GO_LANGUAGE->get_fallback_base_language_file('groups'));

$groups_title = "Grupos de Usuario";
$groups_tab = "Grupos";
$groups_saved = "Grabando la Configuraci&oacute;n.";
$groups_text = "Haga click sobre el grupo para ver sus propiedades.";
$groups_users_in = "Usuarios en el grupo ";
$groups_no_contacts = "Ud. no puede tener contacto con miembros del grupo seleccionado.<br /> Use la Libreta de Direcciones para adicionar miembros a sus contactos.";

$add_group_text = "Ingrese el nombre y haga click sobre 'Ok' para adicionar un nuevo grupo.";
$add_group_fail = "Error al adicionar el grupo. Por favor intentelo nuevamente.";
$add_group_success = "El grupo ha sido adicionado correctamente.";
$add_group_exists = "El nombre ya existe. Por favor ingrese otro nombre.";
$add_group_no_name = "Usted no ha especificado ning&uacute;n nombre.";
$groups_everyone = "Este es un grupo especial que contiene todos los usuarios. Usted no puede modificar este grupo.";
$groups_users_in1 = "Usuario(s) del grupo";
$groups_no_users = "Estos no son usuarios de este grupo.";
$groups_users_in_select = "Seleccione el usuario que usted quiere adicionar a este grupo:";
$groups_new_group = 'Nuevo Grupo';
$groups_members = 'Miembros';
?>
