<?php
require($GO_LANGUAGE->get_fallback_base_language_file('groups'));

$groups_title = "groupes utilisateurs";
$groups_tab = "groupes";
$groups_saved = "Préférences enregistrées.";
$groups_text = "Cliquez sur un groupe pour voir ses propriétés.";
$groups_users_in = "Utilisateurs dans le groupe ";
$groups_no_contacts = "Vous n'avez aucun membre de contact à choisir. Utilisez le carnet d'adresses pour ajouter des membres à vos contacts.";

$add_group_text = "Entrez un nom et cliquez sur 'Ok' pour ajouter un nouveau groupe.";
$add_group_fail = "Impossible d'ajouter le groupe. Merci de réessayer.";
$add_group_success = "Le groupe a été ajouté avec succès.";
$add_group_exists = "Le nom existe déjà. Merci d'en choisir un autre.";
$add_group_no_name = "Vous n'avez pas spécifié de nom.";
$groups_everyone = "Ce groupe est spécial et contient tous les utilisateurs. Vous ne pouvez pas modifier ce groupe.";
$groups_users_in1 = "utilisareur(s) dans le groupe";
$groups_no_users = "Il n'y a pas d'utilisateurs dans ce groupe.";
$groups_users_in_select = "Choisissez les utilisateurs que vous souhaitez ajouter à ce groupe :";

//translation required
$groups_new_group = 'Nouveau groupe';
$groups_members = 'Membres';
?>
