<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('groups'));

$groups_title = "Nhóm người dùng";
$groups_tab = "Các nhóm";
$groups_saved = "Các thay đổi đã được lưu lại.";
$groups_text = "Nhấn vào một nhóm để xem các thông tin.";
$groups_users_in = "Nhưng người trong nhóm ";
$groups_no_contacts = "Bạn không có thành viên nào trong sổ liên hệ để chọn.<br /> Dùng sổ địa chỉ để thêm các thành viên vào sổ.";

$add_group_text = "Nhập tên và nhấn 'Đồng ý' để thêm nhóm mới.";
$add_group_fail = "Thất bại khi thêm nhóm. Xin hãy thử lại.";
$add_group_success = "Thêm nhóm thành công.";
$add_group_exists = "Tên đã có. Hãy chọn tên khác.";
$add_group_no_name = "Bạn chưa đặt tên.";
$groups_everyone = "Nhóm này là một nhóm đặc biệt chứa tất cả mọi thành viên. Bạn không thể thay đổi nhóm này.";
$groups_users_in1 = "Thành viên trong nhóm";
$groups_no_users = "Không có người nào trong nhóm này.";
$groups_users_in_select = "Chọn người mà bạn muốn thêm vào nhóm này:";

//translation required
$groups_new_group = 'Nhóm mới';
$groups_members = 'Các thành viên';

$strGroupLeader = 'Trưởng nhóm';
$cmdSetLeader = 'Chọn trưởng nhóm';
?>
