<?php
require($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = "Libreta de direcciones";
$contacts_no_contacts = "No se encontraron contactos.";
$contacts_members = "miembros";
$contacts_contacts = "contactos";
$contacts_add = "Nuevo contacto";
$contacts_groups = "grupos";
$contacts_other = "Otros contactos";
$contacts_move_to_group = "Mover contactos seleccionados al grupo...";
$groups_no_groups = "Ud. no tiene ning&uacute;n grupo";
$contacts_group = "grupo";
$contacts_empty_group = "Use el combo para mover contactos a este grupo.";
$contacts_this_group = 'este grupo';

$add_contacts_text = "Ingrese en los miembros las direcciones de correo y el c&oacute;digo de autorizaci&oacute;n y haga click en 'Ok'";
$add_contacts_success = "Usuario agregado";
$add_contacts_wrong = "Correo o c&oacute;digo equivocados.";
$add_personal_text = "Haga click en 'Grabar' para agregar el contacto. Los campos marcados con * son obligatorios.";
$contacts_select = "Seleccione los contactos a agregar y haga click en 'Ok'.";
$contacts_select_title = "Contactos";
$contact_profile = "Perfil del contacto";
$user_profile = "Perfil del usuario";
$contacts_authorise = "autorizaci&oacute;n";
$contacts_add_member = "Adicionar este miembro a sus contactos";
$strConfirmSynchronise = "Esto actualizar&aacute; este contacto con informaci&oacute;n ingresada por el mismo . Los cambios manuales hechos por Ud. se perder&aacute;n. Est&aacute; seguro de continuar?";
$contacts_import = "importar";
$contacts_export = "exportar";
$contacts_export_text = "Seleccione el tipo de CSV que desea crear.";
$contacts_delete = "borrar";

$contacts_import_text = "Seleccione un archivo CSV y haga click en 'Ok'";
$contacts_import_text_group = "Seleccione un grupo y un archivo CSV. Haga click en 'Ok'.";
$fbNoFile = "No se recibio ning&uacute;n archivo";
$fbPleaseWait = "Espere mientras se carga el archivo...";

$strNotIncluded = "No se efectu&oacute; la importaci&oacute;n";
$contacts_import_feedback = "Se encontraron las siguientes columnas en su archivo CSV.<br />";
$contacts_import_feedback .= "Seleccionar el grupo que desea importar o crear autom&aacute;ticamente los grupos basados en el archivo.<br />";
$contacts_import_feedback .= " Igualar las columnas del Group-Office columns con las columnas del archivo y verifique que no ha seleccionado dos veces la misma columna.";
$contacts_separator = "Valores separados por";
$contacts_no_separator = "No ingresar un caracter separador.";
$fbFilename = "Nombre de archivo";
$contacts_import_title = "Importar Libreta de Direciones";
$contacts_import_success = "Archivo importado";
$contacts_import_double = "Ha seleccionado una o mas columnas dos veces. Corrija e intente de nuevo.";
$contacts_import_noname = 'Debe seleccionar el nombre del campo';
$contacts_import_incompatible = "Formato de archivo incompatible.<br /><br />Un archivo CSV es un archivo con valores separados por puntos o comas.";
$strMember = "Miembro";
$contact_exist_warning = "<b>Nota:</b> Este usuario ya existe en su lista de contactos.";
$contacts_add_to_group = "Agregar los usuarios seleccionados a contactos en el grupo...";
$contacts_add_to = "Agregar usuarios seleccionados a contactos";
$contacts_add_user = "agregar";
$contacts_edit = "modificar";
$contacts_no_select = "No selecciono nada";
$contacts_this_contact = "este contacto";

$contacts_seperator_text = 'Valores separador por';
$contacts_quote = 'Valores encerrados por';
$contacts_clrf = 'L&iacute;neas terminadas por';
$contacts_auto_group = 'Crear grupos desde el archivo';
$contacts_import_to_group = 'Importar al grupo';

$contacts_search = 'buscar';
$cmdSearch = 'buscar';
$contacts_search_text = "Ingrese una frase de b&uacute;squeda y haga click en 'buscar'. Puede usar * como un caracter de comodin.";
$contacts_results = 'resultado(s)';
$contacts_color = 'Color';
$contacts_colors['black'] = 'Negro';
$contacts_colors['red'] = 'Rojo';
$contacts_colors['green'] = 'Verde';
$contacts_colors['blue'] = 'Azul';
$contacts_colors['pink'] = 'Rosa';
$contacts_colors['orange'] = 'Naranja';
$contacts_colors['brown'] = 'Marr&oacte;n';

$ab_addressbooks = 'Libretas Direcciones';
$ab_owner = 'Propietario';
$ab_subscribed = 'Suscripcion';
$ab_new_ab = 'Nueva Libreta Direcciones';
$ab_addressbook_exists = 'Una libreta de direcciones con ese nombre ya existe';
$ab_addressbook = 'Libreta Direcciones';
$contacts_select_single = 'Click en un contacto para seleccionar a ese persona';

$ab_group_exists = 'Ya existe uno con ese mismo nombre en la libreta de direcciones';

?>
