<?php
require($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = "adressbok";
$contacts_no_contacts = "Inga kontakter funna.";
$contacts_members = "medlemmar";
$contacts_contacts = "kontakter";
$contacts_add = "Ny kontakt";
$contacts_groups = "grupper";
$contacts_other = "Andra kontakter";
$contacts_move_to_group = "Flytta valda kontakter till grupp...";
$groups_no_groups = "Du har inga grupper";
$contacts_group = "grupp";
$contacts_empty_group = "Använd dropdown-menyn för att flytta kontakter till denna grupp.";
$contacts_this_group = 'denna grupp';

$add_contacts_text = "Fyll i medlemmarnas e-postadresser samt authensieringskod och tryck på 'Ok'";
$add_contacts_success = "användaren inlaggd";
$add_contacts_wrong = "Felaktig e-postadress eller authensieringskod.";
$add_personal_text = "Tryck på 'Spara' för att lägga in kontakten. Fälten markerade med * måste fyllas i.";
$contacts_select = "Välj konktakter att lägga till och tryck på 'Ok'.";
$contacts_select_title = "Kontakter";
$contact_profile = "Kontaktprofil";
$user_profile = "Användarprofil";
$contacts_authorise = "authensiering";
$contacts_add_member = "Lägg in denna medlem till dina kontakter";
$strConfirmSynchronise = "Detta kommer att uppdatera denna kontakt med data användaren själv har anget. Manuella
inställningar som du har gjort kommer att försvinna. Är du säker på att du vill fortsätta?";
$contacts_import = "importera";
$contacts_export = "exportera";
$contacts_export_text = "Välj den typ av CSV du vill skapa.";
$contacts_delete = "radera";

$contacts_import_text = "Välj en CSV-fil och tryck på 'Ok'";
$contacts_import_text_group = "Välj en grupp och CSV-filen. Tryck på 'Ok'.";
$fbNoFile = "Ingen fil mottogs";
$fbPleaseWait = "Var god vänta medans filen laddas upp...";

$strNotIncluded = "Importera ej";
$contacts_import_feedback = "Följande kolumner hittades i din CSV-fil.<br />";
$contacts_import_feedback .= "Välj den grupp du vill importera till eller skapa grupperna automatiskt baserat på
kolumnerna i filen.<br />";
$contacts_import_feedback .= " Matcha korresponderande Group_Office kolumner med kolumner från filen och se till
så du väljer kolumner flera gånger.";
$contacts_separator = "Värden separeras med";
$contacts_no_separator = "Du angav inget seperationstecken.";
$fbFilename = "Filnamn";
$contacts_import_title = "Importera Adressbok";
$contacts_import_success = "Filen importerades korrekt";
$contacts_import_double = "Du har valt en eller flera kolumner två gånger. Korrigera detta och försök igen.";
$contacts_import_noname = 'Du måste välja namnfältet.';
$contacts_import_incompatible = "Inkompatibelt filformat.<br /><br />En CSV fil är en fil med värden separerade
med (punkt)komma-tecken.";
$strMember = "Medlem";
$contact_exist_warning = "<b>Notera</b> Denna användare existerar redan i din kontaktlista.";
$contacts_add_to_group = "Lägg in valda användare till kontakter i grupp...";
$contacts_add_to = "Lägg in valda användare till kontakter";
$contacts_add_user = "lägg till";
$contacts_edit = "modifiera";
$contacts_no_select = "Du valde ingenting";
$contacts_this_contact = "denna kontakt";

$contacts_seperator_text = 'Värden separerade av';
$contacts_quote = 'Värden inkaplsade av';
$contacts_clrf = 'Linjer avbryts med';
$contacts_auto_group = 'Skapa grupper automatiskt från fil';
$contacts_import_to_group = 'Importera till grupp';

$contacts_search = 'sök';
$cmdSearch = 'sök';
$contacts_search_text = "Skriv in ett sökord och tryck på 'Sök'. Du kan använda * som matchningar.";
$contacts_results = 'resultat';

//translation required
$contacts_color = 'färg';

$contacts_colors['black'] = 'Svart';
$contacts_colors['red'] = 'Röd';
$contacts_colors['green'] = 'Grön';
$contacts_colors['blue'] = 'Blå';
$contacts_colors['pink'] = 'Rosa';
$contacts_colors['orange'] = 'Orange';
$contacts_colors['brown'] = 'Brun';
?>
