<?php
//Uncomment this line in new translations!
//require($GO_LANGUAGE->get_fallback_base_language_file('sysinfo'));

$si_system_summary = 'Povzetek sistema';
$si_hostname = 'Ime gostitelja';
$si_ip = 'Naslov IP';
$si_kernel = 'Razlièica jedra';
$si_web_server = 'Spletni stre¾nik';
$si_php_version = 'PHP razlièica';
$si_uptime = 'Èas delovanja';
$si_users = 'Trenutni uporabniki';
$si_average_load = 'Povpreèna obremenitev';
$si_days = 'dni';
$si_hours = 'ure';
$si_mins = 'minute';

$si_hardware_summary = 'Pregled strojne opreme';
$si_processors = 'Procesorji';
$si_model = 'Model';
$si_clock = 'Pogosta prijavljanja';
$si_buffersize = 'Velikost medpomnilnika';
$si_bogomips = 'Sistemskih èasovnih enot';
$si_pci = 'PCI naprave';
$si_ide = 'IDE naprave';
$si_scsi = 'SCSI naprave';
$si_capacity = 'Kapaciteta';

$si_network_use = 'Uporaba omre¾ja';
$si_device = 'Naprava';
$si_recieved = 'Prejeto';
$si_sent = 'Poslano';
$si_error = 'Err/Spust';


$si_memory_use = 'Poraba pomnilnika';
$si_type = 'Tip';
$si_percentage_used = 'Odstotkov uporabljeno';
$si_free = 'Sprosti';
$si_used = 'Uporabljeno';
$si_size = 'Velikost';
$si_physical = 'Fizièni pomnilnik';
$si_swap = 'Izmenjalni pomnilnik';

$si_filesystems = 'Priklopljeni datoteèni sistemi';
$si_mount_point = 'Priklopna toèka';
$si_partition = 'Razdelek';
$si_total = 'Skupaj';
$si_show_phpinfo = 'PHP nastavitev ';
?>
