<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'ghi chú';
$no_notes_count = 'ghi chú';
$no_catagory = 'Thê loại';
$no_no_notes = 'Không có ghi chú';
$no_new_note = 'Thêm ghi chú';
$pm_note_exists = 'Ghi chú với tên này đã có.';
$no_catagories = 'Các thể loại';
$no_no_catagories = 'Chưa có thể loại nào được định nghĩa.';
$no_new_catagory= 'Thêm thể loại mới';
$pm_catagory_exists = 'Thể loại này đã có';
$no_catagories_count = 'thể loại';
$no_catagories_count_single = 'Thể loại';
$no_none = 'None';
$no_responsible = 'Chịu trách nhiệm';
$no_due_date = 'Kỳ hạn';

$no_project = 'Dự án';
$no_contact = 'Liên hệ';
$no_file = 'Hồ sơ';

$no_show_all = 'Toàn bộ';
$no_show_own = 'Của riêng';
$no_show_responsible = 'Chịu trách nhiệm';
?>
