<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Chào mừng bạn đến với';
$sum_you_have = 'Bạn có';
$sum_new_messages = 'email <b>chưa đọc</b>';
$sum_new_message = 'email <b>chưa đọc</b>';
$sum_no_new_mail = 'Không có email mới';

$sum_manage_announcements = 'Quản lý các thông báo';
$sum_announcements_count = 'các thông báo';
$sum_announcements_count_single = 'thông báo';
$sum_no_announcements = 'Không có thông báo mới';
$sum_due_time = 'Xem đến tận';
$sum_new_announcement = 'Thêm thông báo';
$sum_private = 'Cá nhân';
?>
